// @ts-nocheck
import React from 'react';
import { Command, Search } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { platformApplications, platformModules, type PlatformApplication, type PlatformModule } from '../platform/platformRegistry';
type CommandItem = { label: string; group: string; path: string; hint?: string; keywords: string[] };
const operational: CommandItem[] = [{ label: 'Find users', group: 'Identity', path: '/app/platform/users', keywords: ['users', 'roles', 'permissions'] }, { label: 'Find organizations', group: 'Workspace', path: '/app/platform/organizations', keywords: ['organizations', 'companies'] }, { label: 'Open support tickets', group: 'Support', path: '/app/platform-preview/support-center/tickets', keywords: ['tickets', 'support'] }, { label: 'Workflow Designer', group: 'Workflows', path: '/app/platform-preview/workflows/designer', keywords: ['workflow', 'designer'] }, { label: 'View Audit Logs', group: 'Governance', path: '/app/platform-preview/audit', keywords: ['audit', 'logs'] }, { label: 'Feature Flags', group: 'Applications', path: '/app/platform-preview/feature-flags', keywords: ['flags'] }, { label: 'API Keys', group: 'Integrations', path: '/app/platform-preview/integrations/api-keys', keywords: ['api', 'keys'] }];
const moduleItems = (items: PlatformModule[]): CommandItem[] => items.map((item) => ({ label: item.title, group: item.category, path: item.route, keywords: item.keywords }));
const applicationItems = (items: PlatformApplication[]): CommandItem[] => items.map((item) => ({ label: `Open ${item.name}`, group: item.status === 'INSTALLED' ? 'Installed Applications' : 'Marketplace', path: item.route, hint: item.status === 'INSTALLED' ? 'Installed' : 'Coming soon', keywords: item.keywords }));
const commands = [...moduleItems(platformModules), ...applicationItems(platformApplications), ...operational];
const PlatformCommandCenter: React.FC = () => { const navigate = useNavigate(); const [open, setOpen] = React.useState(false); const [query, setQuery] = React.useState(''); const inputRef = React.useRef<HTMLInputElement>(null); const results = commands.filter((item) => `${item.label} ${item.group} ${item.keywords.join(' ')}`.toLowerCase().includes(query.toLowerCase())).slice(0, 12); React.useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setOpen(true); } if (event.key === 'Escape') setOpen(false); }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []); React.useEffect(() => { if (open) { setQuery(''); window.setTimeout(() => inputRef.current?.focus(), 0); } }, [open]); const select = (item: CommandItem) => { setOpen(false); navigate(item.path); }; return <><button onClick={() => setOpen(true)} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-500 shadow-sm hover:border-indigo-300 hover:text-indigo-600 dark:border-white/10 dark:bg-slate-950 dark:text-slate-300" aria-label="Open command center"><Search size={15} /><span className="hidden sm:inline">Search platform</span><kbd className="hidden rounded border border-slate-200 px-1.5 py-0.5 text-[10px] font-bold sm:inline dark:border-white/10">Ctrl K</kbd></button>{open && <div className="fixed inset-0 z-50 bg-slate-950/40 p-4 pt-[12vh]" onMouseDown={() => setOpen(false)}><div className="mx-auto max-w-2xl overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-white/10 dark:bg-slate-900" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-center gap-3 border-b border-slate-200 px-4 dark:border-white/10"><Command size={18} className="text-indigo-500" /><input ref={inputRef} value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && results[0]) select(results[0]); }} placeholder="Search applications, modules, settings..." className="h-14 min-w-0 flex-1 bg-transparent text-sm outline-none" /><kbd className="rounded border border-slate-200 px-2 py-1 text-[10px] text-slate-400 dark:border-white/10">ESC</kbd></div><div className="max-h-[55vh] overflow-y-auto p-2">{results.length ? results.map((item) => <button key={`${item.group}-${item.label}`} onClick={() => select(item)} className="flex w-full items-center justify-between rounded-xl px-3 py-3 text-left hover:bg-indigo-50 dark:hover:bg-indigo-500/10"><span><span className="block text-sm font-semibold">{item.label}</span><span className="text-xs text-slate-400">{item.group}{item.hint ? ` · ${item.hint}` : ''}</span></span><span className="text-xs text-slate-400">Open</span></button>) : <p className="px-3 py-8 text-center text-sm text-slate-500">No preview destinations found.</p>}</div></div></div>}</>; };
export default PlatformCommandCenter;
