import Link from "next/link";
import { AppShell } from "./AppShell";
import { requireCurrentApplication } from "@/lib/auth/applications";

export type AdminLink = { label: string; href: string };
const platformGroups = [{ label: "Overview", links: [{ label: "Dashboard", href: "/platform/dashboard" }, { label: "Organizations", href: "/platform/organizations" }, { label: "Companies", href: "/platform/companies" }, { label: "Provision customer", href: "/platform/provisioning" }] }, { label: "Access & billing", links: [{ label: "Users", href: "/platform/users" }, { label: "Applications", href: "/platform/applications" }, { label: "Plans", href: "/platform/plans" }, { label: "Subscriptions", href: "/platform/subscriptions" }, { label: "Invitations", href: "/platform/invitations" }] }, { label: "Governance", links: [{ label: "Audit Activity", href: "/platform/audit" }, { label: "Settings", href: "/platform/settings" }] }];
const customerGroups = [{ label: "Organization", links: [{ label: "Dashboard", href: "/admin/dashboard" }, { label: "Organization", href: "/admin/organization" }, { label: "Companies", href: "/admin/companies" }] }, { label: "People & access", links: [{ label: "Users", href: "/admin/users" }, { label: "Invitations", href: "/admin/invitations" }, { label: "Roles", href: "/admin/roles" }, { label: "Access", href: "/admin/access/current" }, { label: "Applications", href: "/admin/applications" }] }, { label: "Governance", links: [{ label: "Audit Activity", href: "/admin/audit" }, { label: "Settings", href: "/admin/settings" }] }];
export async function AdminShell({ kind, children }: { kind: "platform" | "customer"; children: React.ReactNode }) { await requireCurrentApplication(kind === "platform" ? "PLATFORM_ADMIN" : "CUSTOMER_ADMIN"); const app = kind === "platform" ? "Platform Admin" : "Customer Admin"; return <AppShell app={app} logo="/brands/finance/fallback.svg" alt={`${app} mark`} groups={kind === "platform" ? platformGroups : customerGroups}>{children}</AppShell>; }
export function AdminEmptyPage({ eyebrow, title, description, links = [] }: { eyebrow: string; title: string; description: string; links?: AdminLink[] }) { return <main className="workspace-main"><header className="re-header"><div><span className="re-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div className="re-actions">{links.map((link) => <Link className="re-button primary" href={link.href} key={link.href}>{link.label}</Link>)}</div></header><section className="card panel re-empty"><h2>Coming soon</h2><p>This protected workflow is registered, but its live records and create/edit actions have not been connected yet.</p><Link className="re-button secondary" href="/support">Request workflow setup</Link></section></main>; }
