"use server";
import { redirect } from "next/navigation";
import { headers } from "next/headers";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import { requireMutationContext, requireApplicationContext } from "@/lib/platform/context";
import { getSupabasePublicConfig } from "@/lib/supabase/config";
import { recordRealEstateAudit } from "@/modules/real-estate/services/audit";

const value = (form: FormData, key: string) => String(form.get(key) ?? "").trim();
async function context(permission: string) { return requireMutationContext("HR", permission); }
async function applicationOrigin() { const configured=process.env.NEXT_PUBLIC_SITE_URL?.trim().replace(/\/$/,""); if(configured&&!configured.includes("localhost")&&!configured.includes("127.0.0.1"))return configured; const h=await headers(); const host=h.get("x-forwarded-host")||h.get("host"); if(host&&!host.includes("localhost")&&!host.startsWith("127.0.0.1"))return `${h.get("x-forwarded-proto")||(process.env.NODE_ENV === "production" ? "https" : "http")}://${host}`; return "https://hakika-business-os-frontend.vercel.app"; }
async function deliverInvitation(ctx:any, invitationId:string, rawToken:string) { const {data}=await ctx.supabase.auth.getSession(); const session=data.session; if(!session) throw new Error("Your login session expired. Sign in again and resend the access link."); const {url,publishableKey}=getSupabasePublicConfig(); const inviteUrl=`${await applicationOrigin()}/accept-invitation?token=${rawToken}`; const response=await fetch(`${url}/functions/v1/send-invitation`,{method:"POST",headers:{apikey:publishableKey,Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({invitationId,inviteUrl}),cache:"no-store"}); const result=await response.json().catch(()=>({})) as {error?:string}; if(!response.ok)throw new Error(result.error||"Automatic email/SMS delivery failed. The secure invitation was saved; resend it after checking provider settings."); return result; }

export async function createEmployee(form: FormData) { const ctx=await context("hr.employees.create"); const requestId=randomUUID(); const first_name=value(form,"first_name"), middle_name=value(form,"middle_name")||null, last_name=value(form,"last_name"); if(!first_name||!last_name)return {error:"First and last name are required"}; const {data,error}=await ctx.supabase.schema("hr").rpc("create_employee",{target_org:ctx.organizationId,target_company:ctx.companyId,requested_number:value(form,"employee_number")||null,first_name_value:first_name,middle_name_value:middle_name,last_name_value:last_name,email_value:value(form,"email"),phone_value:value(form,"phone"),employment_type_value:value(form,"employment_type")||"permanent",employment_status_value:value(form,"employment_status")||"draft",start_date_value:value(form,"employment_start_date")||null,probation_end_date_value:value(form,"probation_end_date")||null,pwd_status_value:form.get("pwd_status")==="on",current_residence_value:value(form,"current_residence"),original_home_value:value(form,"original_home"),notes_value:value(form,"notes")}).single(); const created=data as {employee_id:string}|null; if(error||!created){console.error("[hr.employee.create] failed",{requestId,code:error?.code??"NO_DATA"});return {error:`We couldn’t create the employee. No employee was created. Reference: ${requestId.slice(0,8)}`};} const {error:profileError}=await ctx.supabase.schema("hr").from("employees").update({date_of_birth:value(form,"date_of_birth")||null}).eq("id",created.employee_id).eq("organization_id",ctx.organizationId); if(profileError)return {error:`Employee was created, but the date of birth could not be saved. Try editing the employee. Reference: ${requestId.slice(0,8)}`}; if(form.get("prepare_invitation")==="on"){const invitation=await prepareEmployeeInvitation(created.employee_id);if(invitation.error)return {error:`Employee created, but access was not sent: ${invitation.error}`};} redirect(`/hr/employees/${created.employee_id}`); }

export async function prepareEmployeeInvitation(employeeId:string){const ctx=await context("hr.employee_access.prepare_invitation");const {data:employee}=await ctx.supabase.schema("hr").from("employees").select("id,display_name,email,phone,employee_number,portal_access_status").eq("id",employeeId).eq("organization_id",ctx.organizationId).maybeSingle();if(!employee)return {error:"Employee not found"};if(!employee.email&&!employee.phone)return {error:"Add a login email or verified phone before preparing access"};const raw=randomBytes(32).toString("hex"),token_hash=createHash("sha256").update(raw).digest("hex"),expires_at=new Date(Date.now()+48*60*60*1000).toISOString();await ctx.supabase.schema("iam").from("invitations").update({status:"revoked",revoked_at:new Date().toISOString()}).eq("organization_id",ctx.organizationId).eq("employee_id",employeeId).eq("status","pending");const {data:invitation,error}=await ctx.supabase.schema("iam").from("invitations").insert({organization_id:ctx.organizationId,employee_id:employeeId,email:employee.email,phone:employee.phone,token_hash,expires_at,invited_by:ctx.userId,delivery_channel:employee.email&&employee.phone?"both":employee.email?"email":"sms",delivery_status:"pending"}).select("id,expires_at").single();if(error||!invitation)return {error:error?.code === "42501" ? "HR access invitations are not enabled for your role. Ask an organization administrator to grant employee invitation permission." : "Could not prepare invitation. Try again shortly."};await ctx.supabase.schema("hr").from("employees").update({portal_access_status:"invited"}).eq("id",employeeId).eq("organization_id",ctx.organizationId);await recordRealEstateAudit(ctx.supabase,{userId:ctx.userId,organizationId:ctx.organizationId,companyId:ctx.companyId,applicationKey:"HR",action:"employee.invitation_prepared",entityType:"employee_invitation",entityId:invitation.id,label:employee.display_name});try{const delivery=await deliverInvitation(ctx,invitation.id,raw);return {ok:true,expiresAt:invitation.expires_at,delivery};}catch(error){return {error:error instanceof Error?error.message:"Automatic email/SMS delivery failed. The invitation was saved."};}}

export async function updateEmployee(id:string,form:FormData){const ctx=await context("hr.employees.update");const first_name=value(form,"first_name"),middle_name=value(form,"middle_name")||null,last_name=value(form,"last_name");if(!first_name||!last_name)return {error:"First and last name are required"};let q=ctx.supabase.schema("hr").from("employees").update({first_name,middle_name,last_name,display_name:[first_name,middle_name,last_name].filter(Boolean).join(" "),email:value(form,"email").toLowerCase()||null,phone:value(form,"phone")||null,date_of_birth:value(form,"date_of_birth")||null,current_residence:value(form,"current_residence")||null,original_home:value(form,"original_home")||null,notes:value(form,"notes")||null,employment_type:value(form,"employment_type")||"permanent",employment_status:value(form,"employment_status")||"draft",employment_start_date:value(form,"employment_start_date")||null,probation_end_date:value(form,"probation_end_date")||null,updated_by:ctx.userId}).eq("id",id).eq("organization_id",ctx.organizationId);if(ctx.companyId)q=q.eq("company_id",ctx.companyId);const {error}=await q;if(error)return {error:"Employee could not be updated. Try again shortly."};redirect(`/hr/employees/${id}`);}
export async function archiveEmployee(id:string,reason:string){const ctx=await context("hr.employees.archive");if(!reason.trim())return {error:"Archive reason is required"};let q=ctx.supabase.schema("hr").from("employees").update({employment_status:"archived",archived_at:new Date().toISOString(),archived_by:ctx.userId,archive_reason:reason,updated_by:ctx.userId}).eq("id",id).eq("organization_id",ctx.organizationId);if(ctx.companyId)q=q.eq("company_id",ctx.companyId);const {error}=await q;if(error)return {error:"Employee could not be archived. Try again shortly."};await recordRealEstateAudit(ctx.supabase,{userId:ctx.userId,organizationId:ctx.organizationId,companyId:ctx.companyId,applicationKey:"HR",action:"employee.archived",entityType:"employee",entityId:id});redirect("/hr/employees");}
export async function reinstateEmployee(id:string){const ctx=await context("hr.employees.reinstate");let q=ctx.supabase.schema("hr").from("employees").update({employment_status:"active",archived_at:null,archived_by:null,archive_reason:null,updated_by:ctx.userId}).eq("id",id).eq("organization_id",ctx.organizationId);if(ctx.companyId)q=q.eq("company_id",ctx.companyId);const {error}=await q;if(error)return {error:"Employee could not be reinstated. Try again shortly."};await recordRealEstateAudit(ctx.supabase,{userId:ctx.userId,organizationId:ctx.organizationId,companyId:ctx.companyId,applicationKey:"HR",action:"employee.reinstated",entityType:"employee",entityId:id});redirect(`/hr/employees/${id}`);}
export async function listHrDepartments(){const ctx=await requireApplicationContext("HR");return ctx.supabase.schema("hr").from("departments").select("id,name").eq("organization_id",ctx.organizationId).is("archived_at",null).order("name");}
