"use server";
import { redirect } from "next/navigation";
import { requireMutationContext, requireApplicationContext } from "@/lib/platform/context";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import { recordRealEstateAudit } from "@/modules/real-estate/services/audit";
const value = (form: FormData, key: string) => String(form.get(key) ?? "").trim();
async function context(permission: string) { return requireMutationContext("HR", permission); }
export async function createEmployee(form: FormData) { const ctx=await context("hr.employees.create"); const requestId=randomUUID(); const first_name=value(form,"first_name"), middle_name=value(form,"middle_name")||null, last_name=value(form,"last_name"); if(!first_name||!last_name)return {error:"First and last name are required"}; const {data,error}=await ctx.supabase.schema("hr").rpc("create_employee",{target_org:ctx.organizationId,target_company:ctx.companyId,requested_number:value(form,"employee_number")||null,first_name_value:first_name,middle_name_value:middle_name,last_name_value:last_name,email_value:value(form,"email"),phone_value:value(form,"phone"),employment_type_value:value(form,"employment_type")||"permanent",employment_status_value:value(form,"employment_status")||"draft",start_date_value:value(form,"employment_start_date")||null,probation_end_date_value:value(form,"probation_end_date")||null,pwd_status_value:form.get("pwd_status")==="on",current_residence_value:value(form,"current_residence"),original_home_value:value(form,"original_home"),notes_value:value(form,"notes")}).single(); const created=data as {employee_id:string}|null; if(error||!created){console.error("[hr.employee.create] failed",{requestId,stage:"atomic_create",userId:ctx.userId,organizationId:ctx.organizationId,companyId:ctx.companyId,applicationKey:"HR",code:error?.code??"NO_DATA",timestamp:new Date().toISOString()});return {error:`We couldn’t create the employee. No employee was created. Try again or contact support. Reference: ${requestId.slice(0,8)}`};} if(form.get("prepare_invitation")==="on"){const invitation=await prepareEmployeeInvitation(created.employee_id);if(invitation.error)return {error:`Employee created. ${invitation.error}`};} redirect(`/hr/employees/${created.employee_id}`); }
export async function prepareEmployeeInvitation(employeeId:string){const ctx=await context("hr.employee_access.prepare_invitation");const {data:employee}=await ctx.supabase.schema("hr").from("employees").select("id,display_name,email,phone,employee_number,portal_access_status").eq("id",employeeId).eq("organization_id",ctx.organizationId).maybeSingle();if(!employee)return {error:"Employee not found"};if(!employee.email&&!employee.phone)return {error:"Add a login email or verified phone before preparing access"};const raw=randomBytes(32).toString("hex"),token_hash=createHash("sha256").update(raw).digest("hex"),expires_at=new Date(Date.now()+24*60*60*1000).toISOString();await ctx.supabase.schema("iam").from("invitations").update({status:"revoked",revoked_at:new Date().toISOString()}).eq("organization_id",ctx.organizationId).eq("employee_id",employeeId).eq("status","pending");const {data:invitation,error}=await ctx.supabase.schema("iam").from("invitations").insert({organization_id:ctx.organizationId,employee_id:employeeId,email:employee.email,phone:employee.phone,token_hash,expires_at,invited_by:ctx.userId,delivery_channel:employee.email?"email":"sms",delivery_status:"pending"}).select("id,expires_at").single();if(error||!invitation)return {error:"Could not prepare invitation. Try again shortly."};await ctx.supabase.schema("hr").from("employees").update({portal_access_status:"invited"}).eq("id",employeeId).eq("organization_id",ctx.organizationId);await recordRealEstateAudit(ctx.supabase,{userId:ctx.userId,organizationId:ctx.organizationId,companyId:ctx.companyId,action:"employee.invitation_prepared",entityType:"employee_invitation",entityId:invitation.id,label:employee.display_name});return {ok:true,expiresAt:invitation.expires_at};}
export async function updateEmployee(id:string,form:FormData){const ctx=await context("hr.employees.update");const first_name=value(form,"first_name"),middle_name=value(form,"middle_name")||null,last_name=value(form,"last_name");if(!first_name||!last_name)return {error:"First and last name are required"};let q=ctx.supabase.schema("hr").from("employees").update({first_name,middle_name,last_name,display_name:[first_name,middle_name,last_name].filter(Boolean).join(" "),email:value(form,"email").toLowerCase()||null,phone:value(form,"phone")||null,employment_type:value(form,"employment_type")||"permanent",employment_status:value(form,"employment_status")||"draft",employment_start_date:value(form,"employment_start_date")||null,updated_by:ctx.userId}).eq("id",id).eq("organization_id",ctx.organizationId);if(ctx.companyId)q=q.eq("company_id",ctx.companyId);const {error}=await q;if(error)return {error:"Employee could not be updated. Try again shortly."};redirect(`/hr/employees/${id}`);}
export async function archiveEmployee(id:string,reason:string){const ctx=await context("hr.employees.archive");if(!reason.trim())return {error:"Archive reason is required"};let q=ctx.supabase.schema("hr").from("employees").update({employment_status:"archived",archived_at:new Date().toISOString(),archived_by:ctx.userId,archive_reason:reason,updated_by:ctx.userId}).eq("id",id).eq("organization_id",ctx.organizationId);if(ctx.companyId)q=q.eq("company_id",ctx.companyId);const {error}=await q;if(error)return {error:"Employee could not be archived. Try again shortly."};await recordRealEstateAudit(ctx.supabase,{userId:ctx.userId,organizationId:ctx.organizationId,companyId:ctx.companyId,applicationKey:"HR",action:"employee.archived",entityType:"employee",entityId:id});redirect("/hr/employees");}
export async function reinstateEmployee(id:string){const ctx=await context("hr.employees.reinstate");let q=ctx.supabase.schema("hr").from("employees").update({employment_status:"active",archived_at:null,archived_by:null,archive_reason:null,updated_by:ctx.userId}).eq("id",id).eq("organization_id",ctx.organizationId);if(ctx.companyId)q=q.eq("company_id",ctx.companyId);const {error}=await q;if(error)return {error:"Employee could not be reinstated. Try again shortly."};await recordRealEstateAudit(ctx.supabase,{userId:ctx.userId,organizationId:ctx.organizationId,companyId:ctx.companyId,applicationKey:"HR",action:"employee.reinstated",entityType:"employee",entityId:id});redirect(`/hr/employees/${id}`);}
export async function listHrDepartments(){const ctx=await requireApplicationContext("HR");return ctx.supabase.schema("hr").from("departments").select("id,name").eq("organization_id",ctx.organizationId).is("archived_at",null).order("name");}
