import { REAL_ESTATE_PERMISSIONS as P } from "../permissions/catalog";
import type { RealEstateNavigationItem } from "../types";

const item = (id: string, label: string, slug: string, requiredPermission: string): RealEstateNavigationItem => ({ id, label, href: `/real-estate/${slug}`, requiredPermission, requiredApplication: "REAL_ESTATE" });
const admin = (id: string, label: string, slug: string, permission: string) => item(id, label, slug, permission);

export const REAL_ESTATE_NAVIGATION: ReadonlyArray<{ id: string; label: string; items: ReadonlyArray<RealEstateNavigationItem> }> = [
  { id: "overview", label: "Overview", items: [item("dashboard", "Dashboard", "dashboard", P.dashboardRead), item("properties", "Properties", "properties", P.propertiesRead), item("units", "Houses / Units", "units", P.unitsRead), item("inspections", "Inspections", "inspections", P.propertiesRead), item("ledger", "Global Ledger", "ledger", P.dashboardRead), item("notes", "Notes & Findings", "notes", P.propertiesRead)] },
  { id: "tenants", label: "Tenants", items: [item("tenant-directory", "Tenant Directory", "tenants", P.tenantsRead), item("applications", "Applications", "applications", P.tenantsRead), item("leases", "Leases", "leases", P.leasesRead), item("move-in", "Move In", "move-in", P.leasesRead), item("move-out", "Move Out", "move-out", P.leasesRead), item("deposits", "Deposits", "deposits", P.paymentsRead)] },
  { id: "billing", label: "Invoices & Billing", items: [item("invoices", "Invoices", "invoices", P.invoicesRead), item("recurring-billing", "Recurring Billing", "recurring-billing", P.invoicesRead), item("billing-schedules", "Billing Schedules", "billing-schedules", P.invoicesRead), item("rent-charges", "Rent Charges", "rent-charges", P.invoicesRead), item("utilities", "Utilities", "utilities", P.invoicesRead), item("penalties", "Penalties", "penalties", P.invoicesRead), item("credit-notes", "Credit Notes", "credit-notes", P.invoicesRead), item("receipts", "Receipts", "receipts", P.paymentsRead), item("statements", "Statements", "statements", P.invoicesRead)] },
  { id: "payments", label: "Payments", items: [item("payments", "Payment Directory", "payments", P.paymentsRead), item("allocation", "Allocation", "payment-allocation", P.paymentsAllocate), item("reconciliation", "Reconciliation", "reconciliation", P.paymentsReconcile), item("mpesa", "M-Pesa", "mpesa", P.paymentsRead), item("mpesa-transactions", "M-Pesa Transactions", "mpesa-transactions", P.paymentsRead), item("unmatched", "Unmatched Payments", "unmatched-payments", P.paymentsRead), item("split", "Split Payments", "split-payments", P.paymentsAllocate), item("reversals-refunds", "Reversals & Refunds", "reversals-refunds", P.paymentsRead)] },
  { id: "reports", label: "Collections & Reports", items: [item("collections", "Collections", "collections", P.paymentsRead), item("arrears", "Arrears", "arrears", P.invoicesRead), item("landlord-statements", "Landlord Statements", "landlord-statements", P.propertiesRead), item("occupancy", "Occupancy", "occupancy", P.unitsRead), item("performance", "Property Performance", "property-performance", P.propertiesRead), item("income-expenses", "Income & Expenses", "income-expenses", P.dashboardRead), item("exports", "Exports", "exports", P.reportsExport)] },
  { id: "administration", label: "Administration", items: [admin("users", "Users", "users", "admin.members.read"), admin("roles", "Roles", "roles-permissions", "admin.roles.read"), item("company-settings", "Company Settings", "company-settings", P.settingsManage), item("property-settings", "Property Settings", "property-settings", P.settingsManage), item("invoice-settings", "Invoice Settings", "invoice-settings", P.settingsManage), item("payment-settings", "Payment Settings", "payment-settings", P.settingsManage), item("notification-templates", "Notification Templates", "notification-templates", P.settingsManage), admin("audit", "Audit Activity", "audit-activity", "admin.audit.read")] },
];

export const realEstateNavigationGroups = REAL_ESTATE_NAVIGATION.map((group) => ({ label: group.label, links: group.items.map(({ label, href }) => ({ label, href })) }));
export const realEstateNavigationItems = REAL_ESTATE_NAVIGATION.flatMap((group) => group.items);
