import Link from "next/link";
import { getAuthenticatedTenant } from "@/modules/real-estate/tenant-billing";

export default async function TenantDashboard() {
  const { ctx, tenant } = await getAuthenticatedTenant();
  if (!tenant) return <main className="re-main"><header className="re-header"><div><span className="re-eyebrow">Tenant portal</span><h1>Tenant portal setup</h1><p>Your account is authenticated, but it is not linked to a tenant record yet.</p></div></header><section className="re-surface re-empty-state"><h2>Tenant identity not linked</h2><p>Ask your property manager to connect your portal account. No tenant ID is accepted from the browser.</p></section></main>;
  const [{ data: lease }, { data: invoices }, { data: payments }] = await Promise.all([
    ctx.supabase.schema("real_estate").from("leases").select("lease_number,start_date,end_date,rent_amount_minor,property_id,unit_id,status").eq("tenant_id", tenant.id).eq("organization_id", ctx.organizationId).eq("status", "active").is("archived_at", null).maybeSingle(),
    ctx.supabase.schema("real_estate").from("invoices").select("id,total_minor,balance_due_minor,status,billing_month").eq("tenant_id", tenant.id).eq("organization_id", ctx.organizationId).is("archived_at", null).order("billing_month", { ascending: false }).limit(5),
    ctx.supabase.schema("real_estate").from("payments").select("id,amount_minor,paid_at,payment_method,status").eq("tenant_id", tenant.id).eq("organization_id", ctx.organizationId).is("archived_at", null).order("paid_at", { ascending: false }).limit(5),
  ]);
  const [{ data: property }, { data: unit }] = await Promise.all([
    ctx.supabase.schema("real_estate").from("properties").select("name").eq("id", lease?.property_id ?? "00000000-0000-0000-0000-000000000000").maybeSingle(),
    ctx.supabase.schema("real_estate").from("units").select("unit_number").eq("id", lease?.unit_id ?? "00000000-0000-0000-0000-000000000000").maybeSingle(),
  ]);
  const balance = (invoices ?? []).reduce((sum, row: any) => sum + Number(row.balance_due_minor || 0), 0);
  return <main className="re-main"><header className="re-header"><div><span className="re-eyebrow">Tenant portal</span><h1>Welcome, {tenant.full_name}</h1><p>Manage your lease, rent, receipts, notices and messages in one place.</p></div><Link className="re-button secondary" href="/tenant/lease/download">Download lease</Link></header><div className="re-stats"><div className="re-stat"><span>Property</span><strong>{property?.name || "Not assigned"}</strong></div><div className="re-stat"><span>Unit</span><strong>{unit?.unit_number || "Not assigned"}</strong></div><div className="re-stat"><span>Monthly rent</span><strong>KES {(Number(lease?.rent_amount_minor || 0) / 100).toLocaleString()}</strong></div><div className="re-stat"><span>Balance due</span><strong>KES {(balance / 100).toLocaleString()}</strong></div></div><div className="re-detail-grid"><section className="re-surface"><span className="re-eyebrow">Lease summary</span><h2>{lease?.lease_number || "No active lease"}</h2><dl><dt>Status</dt><dd>{lease?.status || "Not assigned"}</dd><dt>Lease period</dt><dd>{lease ? `${lease.start_date} to ${lease.end_date || "Open-ended"}` : "—"}</dd><dt>Property / unit</dt><dd>{property?.name || "—"} · {unit?.unit_number || "—"}</dd></dl><div className="re-actions"><Link className="re-button primary" href="/tenant/lease">View lease</Link><Link className="re-button secondary" href="/tenant/maintenance">Submit maintenance request</Link></div></section><section className="re-surface"><span className="re-eyebrow">Recent invoices</span><h2>Billing activity</h2>{(invoices ?? []).length ? <div className="re-list">{invoices!.slice(0, 3).map((row: any) => <div className="re-list-row" key={row.id}><span>{row.billing_month}</span><strong>KES {(Number(row.total_minor || 0) / 100).toLocaleString()}</strong><span className="re-badge">{row.status}</span></div>)}</div> : <p>No invoices recorded yet.</p>}<Link className="re-row-action" href="/tenant/invoices">View all invoices</Link></section></div><section className="re-surface"><div className="re-section-head"><div><span className="re-eyebrow">Recent payments</span><h2>Payment history</h2></div><Link className="re-button secondary" href="/tenant/payments">View payments</Link></div>{(payments ?? []).length ? <div className="re-list">{payments!.slice(0, 3).map((row: any) => <div className="re-list-row" key={row.id}><span>{row.paid_at ? new Date(row.paid_at).toLocaleDateString() : "—"}</span><strong>KES {(Number(row.amount_minor || 0) / 100).toLocaleString()}</strong><span>{row.payment_method || "—"}</span><span className="re-badge">{row.status}</span></div>)}</div> : <p>No payment records yet.</p>}</section></main>;
}
