import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { PropertyInput, UnitInput, AssetInput } from "../schemas";

type Scope = { organizationId: string; companyId: string | null };
const scoped = <T extends { eq: (column: string, value: string) => T }>(query: T, scope: Scope) => scope.companyId ? query.eq("company_id", scope.companyId) : query;

export async function listProperties(db: SupabaseClient, scope: Scope, search = "", options: { page?: number; pageSize?: number; type?: string; status?: string; sort?: string } = {}) { let q = db.schema("real_estate").from("properties").select("*, units:units(count)", { count: "exact" }).eq("organization_id", scope.organizationId).is("archived_at", null).order(options.sort === "name" ? "name" : "created_at", { ascending: false }); q = scoped(q, scope); if (search) q = q.or(`name.ilike.%${search}%,property_code.ilike.%${search}%`); if (options.type) q=q.eq("property_type",options.type); if (options.status) q=q.eq("status",options.status); if(options.pageSize)q=q.range(((options.page??1)-1)*options.pageSize,(options.page??1)*options.pageSize-1); return q; }
export async function getProperty(db: SupabaseClient, scope: Scope, id: string) { let q = db.schema("real_estate").from("properties").select("*, units:units(id,unit_number,status,monthly_rent_minor,unit_type)").eq("id", id).eq("organization_id", scope.organizationId).is("archived_at", null); q = scoped(q, scope); return q.maybeSingle(); }
export async function listUnits(db: SupabaseClient, scope: Scope, search = "", options: { page?: number; pageSize?: number; propertyId?: string; type?: string; status?: string } = {}) { let q = db.schema("real_estate").from("units").select("*, property:properties(id,name,property_code)", { count: "exact" }).eq("organization_id", scope.organizationId).is("archived_at", null).order("created_at", { ascending: false }); q = scoped(q, scope); if (search) q = q.ilike("unit_number", `%${search}%`); if(options.propertyId)q=q.eq("property_id",options.propertyId);if(options.type)q=q.eq("unit_type",options.type);if(options.status)q=q.eq("status",options.status);if(options.pageSize)q=q.range(((options.page??1)-1)*options.pageSize,(options.page??1)*options.pageSize-1); return q; }
export async function getUnit(db: SupabaseClient, scope: Scope, id: string) { let q = db.schema("real_estate").from("units").select("*, property:properties(id,name,property_code), unit_assets(id,asset_name,status,quantity)").eq("id", id).eq("organization_id", scope.organizationId).is("archived_at", null); q = scoped(q, scope); return q.maybeSingle(); }
function propertyPayload(input: PropertyInput) { const { property_config, planned_unit_mix, electricity_bill_amount, water_bill_amount, keys_deposit_amount, ...rest } = input; let config: Record<string, unknown> = {}; try { config = property_config ? JSON.parse(property_config) : {}; } catch { config = {}; } config = { ...config, electricity_bill_amount, water_bill_amount, keys_deposit_amount }; let mix: unknown[] = []; try { mix = planned_unit_mix ? JSON.parse(planned_unit_mix) : []; } catch { mix = []; } return { ...rest, planned_unit_count: input.planned_unit_count ?? 0, planned_unit_mix: mix, property_config: config, amenities: input.amenities ? input.amenities.split(",").map((x) => x.trim()).filter(Boolean) : [] }; }
export async function insertProperty(db: SupabaseClient, scope: Scope, userId: string, input: PropertyInput) { return db.schema("real_estate").from("properties").insert({ ...propertyPayload(input), organization_id: scope.organizationId, company_id: scope.companyId, created_by: userId }).select("id").single(); }
export async function updateProperty(db: SupabaseClient, scope: Scope, userId: string, id: string, input: PropertyInput) { let q = db.schema("real_estate").from("properties").update({ ...propertyPayload(input), updated_by: userId }).eq("id", id).eq("organization_id", scope.organizationId).is("archived_at", null); q = scoped(q, scope); return q.select("id").single(); }
function unitPayload(input: UnitInput) { const { property_id, monthly_rent, unit_config, electricity_bill_amount, water_bill_amount, keys_deposit_amount, rent_deposit_amount, ...rest } = input; let config: Record<string, unknown> = {}; try { config = unit_config ? JSON.parse(unit_config) : {}; } catch { config = {}; } config = { ...config, electricity_bill_amount, water_bill_amount, keys_deposit_amount, rent_deposit_amount }; return { ...rest, property_id, monthly_rent_minor: Math.round(monthly_rent * 100), unit_config: config }; }
export async function insertUnit(db: SupabaseClient, scope: Scope, userId: string, input: UnitInput) { return db.schema("real_estate").from("units").insert({ ...unitPayload(input), organization_id: scope.organizationId, company_id: scope.companyId, created_by: userId }).select("id").single(); }
export async function updateUnit(db: SupabaseClient, scope: Scope, userId: string, id: string, input: UnitInput) { let q = db.schema("real_estate").from("units").update({ ...unitPayload(input), updated_by: userId }).eq("id", id).eq("organization_id", scope.organizationId).is("archived_at", null); q = scoped(q, scope); return q.select("id").single(); }
export async function insertAsset(db: SupabaseClient, scope: Scope, userId: string, input: AssetInput) { let unit = db.schema("real_estate").from("units").select("property_id").eq("id", input.unit_id).eq("organization_id", scope.organizationId); unit = scoped(unit, scope); return db.schema("real_estate").from("unit_assets").insert({ ...input, organization_id: scope.organizationId, company_id: scope.companyId, property_id: (await unit.single()).data?.property_id, created_by: userId }).select("id").single(); }
