import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { PropertyInput, UnitInput, AssetInput } from "../schemas";

export async function listProperties(db: SupabaseClient, scope: { organizationId: string; companyId: string | null }, search = "", options: { page?: number; pageSize?: number; type?: string; status?: string; sort?: string } = {}) {
  let q = db.schema("real_estate").from("properties").select("*, units:units(count)", { count: "exact" }).eq("organization_id", scope.organizationId).is("archived_at", null).order(options.sort === "name" ? "name" : "created_at", { ascending: false });
  if (scope.companyId) q = q.eq("company_id", scope.companyId); if (search) q = q.or(`name.ilike.%${search}%,property_code.ilike.%${search}%`); if (options.type) q=q.eq("property_type",options.type); if (options.status) q=q.eq("status",options.status); if(options.pageSize) q=q.range(((options.page??1)-1)*options.pageSize,(options.page??1)*options.pageSize-1); return q;
}
export async function getProperty(db: SupabaseClient, scope: { organizationId: string; companyId: string | null }, id: string) { let q = db.schema("real_estate").from("properties").select("*, units:units(id,unit_number,status,monthly_rent_minor,unit_type)").eq("id", id).eq("organization_id", scope.organizationId).is("archived_at", null); if (scope.companyId) q = q.eq("company_id", scope.companyId); return q.maybeSingle(); }
export async function listUnits(db: SupabaseClient, scope: { organizationId: string; companyId: string | null }, search = "", options: { page?: number; pageSize?: number; propertyId?: string; type?: string; status?: string } = {}) { let q = db.schema("real_estate").from("units").select("*, property:properties(id,name,property_code)", { count: "exact" }).eq("organization_id", scope.organizationId).is("archived_at", null).order("created_at", { ascending: false }); if (scope.companyId) q = q.eq("company_id", scope.companyId); if (search) q = q.ilike("unit_number", `%${search}%`); if(options.propertyId)q=q.eq("property_id",options.propertyId);if(options.type)q=q.eq("unit_type",options.type);if(options.status)q=q.eq("status",options.status);if(options.pageSize)q=q.range(((options.page??1)-1)*options.pageSize,(options.page??1)*options.pageSize-1); return q; }
export async function getUnit(db: SupabaseClient, scope: { organizationId: string; companyId: string | null }, id: string) { let q = db.schema("real_estate").from("units").select("*, property:properties(id,name,property_code), unit_assets(id,asset_name,status,quantity)").eq("id", id).eq("organization_id", scope.organizationId).is("archived_at", null); if (scope.companyId) q = q.eq("company_id", scope.companyId); return q.maybeSingle(); }
export async function insertProperty(db: SupabaseClient, scope: { organizationId: string; companyId: string }, userId: string, input: PropertyInput) { return db.schema("real_estate").from("properties").insert({ ...input, planned_unit_count: input.planned_unit_count ?? 0, amenities: input.amenities ? input.amenities.split(",").map((x) => x.trim()).filter(Boolean) : [], organization_id: scope.organizationId, company_id: scope.companyId, created_by: userId }).select("id").single(); }
export async function updateProperty(db: SupabaseClient, scope: { organizationId: string; companyId: string }, userId: string, id: string, input: PropertyInput) { return db.schema("real_estate").from("properties").update({ ...input, amenities: input.amenities ? input.amenities.split(",").map((x) => x.trim()).filter(Boolean) : [], updated_by: userId }).eq("id", id).eq("organization_id", scope.organizationId).eq("company_id", scope.companyId).is("archived_at", null).select("id").single(); }
export async function insertUnit(db: SupabaseClient, scope: { organizationId: string; companyId: string }, userId: string, input: UnitInput) { const { property_id, monthly_rent, ...rest } = input; return db.schema("real_estate").from("units").insert({ ...rest, property_id, monthly_rent_minor: Math.round(monthly_rent * 100), organization_id: scope.organizationId, company_id: scope.companyId, created_by: userId }).select("id").single(); }
export async function updateUnit(db: SupabaseClient, scope: { organizationId: string; companyId: string }, userId: string, id: string, input: UnitInput) { const { property_id, monthly_rent, ...rest } = input; return db.schema("real_estate").from("units").update({ ...rest, property_id, monthly_rent_minor: Math.round(monthly_rent * 100), updated_by: userId }).eq("id", id).eq("organization_id", scope.organizationId).eq("company_id", scope.companyId).is("archived_at", null).select("id").single(); }
export async function insertAsset(db: SupabaseClient, scope: { organizationId: string; companyId: string }, userId: string, input: AssetInput) { return db.schema("real_estate").from("unit_assets").insert({ ...input, organization_id: scope.organizationId, company_id: scope.companyId, property_id: (await db.schema("real_estate").from("units").select("property_id").eq("id", input.unit_id).eq("organization_id", scope.organizationId).eq("company_id", scope.companyId).single()).data?.property_id, created_by: userId }).select("id").single(); }
