// @ts-nocheck
import { AlertTriangle, CheckCircle, Clock } from 'lucide-react';
import { supabase } from '../utils/supabase';

// Interfaces based on KRA eTIMS specifications
export interface ETimsTraderInfo {
    pin: string;
    tradingName: string;
    branchName: string;
    branchCode: string;
    deviceSerialNumber: string;
    isVerified: boolean;
}

export interface ETimsInvoiceItem {
    description: string;
    quantity: number;
    unitPrice: number;
    taxCode: 'A' | 'B' | 'C' | 'D' | 'E'; // Standard KRA Tax Codes
    totalAmount: number;
}

export interface ETimsInvoice {
    invoiceNumber?: string; // Generated by system
    etimsControlNumber?: string; // Returned by KRA
    qrCodeUrl?: string; // Returned by KRA
    customerPin?: string;
    customerName?: string;
    items: ETimsInvoiceItem[];
    totalTax: number;
    totalAmount: number;
    date: string;
    status: 'PENDING' | 'SUBMITTED' | 'VERIFIED' | 'FAILED';
}

export interface ETimsResponse {
    success: boolean;
    message: string;
    data?: any;
    timsCode?: string; // The control unit number
}

// Mock Service Implementation
class ETimsService {
    private traderInfo: ETimsTraderInfo = {
        pin: 'P051234567Z',
        tradingName: 'HAKIKA OPERATIONS LTD',
        branchName: 'HQ',
        branchCode: '00',
        deviceSerialNumber: 'OSCU-8821-3921',
        isVerified: true
    };

    /**
     * Simulates initialization of the OSCU (Online Sales Control Unit)
     */
    async initializeDevice(): Promise<ETimsResponse> {
        console.log('[eTIMS] Initializing OSCU Device...');
        return new Promise((resolve) => {
            setTimeout(() => {
                console.log('[eTIMS] Device Connected: ', this.traderInfo.deviceSerialNumber);
                resolve({
                    success: true,
                    message: 'OSCU Device Initialized Successfully',
                    data: this.traderInfo
                });
            }, 1000);
        });
    }

    /**
     * Simulates sending an invoice to KRA eTIMS and persists the result to Supabase
     */
    async sendInvoice(invoice: ETimsInvoice, module?: string, referenceId?: string): Promise<ETimsResponse> {
        console.log(`[eTIMS] Sending Invoice Data for ${module || 'unknown'}...`, invoice);

        return new Promise(async (resolve) => {
            setTimeout(async () => {
                const controlNumber = `KRA${Date.now().toString().slice(-8)}MT`;
                const qrUrl = `https://itax.kra.go.ke/verify?id=${controlNumber}`;

                console.log('[eTIMS] Invoice Verified. Control Number:', controlNumber);

                const response: ETimsResponse = {
                    success: true,
                    message: 'Invoice Signed and Verified',
                    timsCode: controlNumber,
                    data: {
                        qrCode: qrUrl,
                        dateVerified: new Date().toISOString()
                    }
                };

                // PERSISTENCE LOGIC
                if (module && referenceId) {
                    try {
                        // 1. Log to generic submissions table
                        await supabase.from('etims_submissions').insert({
                            module,
                            reference_id: referenceId,
                            tims_code: controlNumber,
                            qr_url: qrUrl,
                            status: 'success',
                            raw_request: invoice,
                            raw_response: response
                        });

                        // 2. If it's a real estate invoice, update the re_invoices table
                        if (module === 'real_estate') {
                            await supabase.from('re_invoices').update({
                                etims_control_number: controlNumber,
                                etims_verification_url: qrUrl,
                                etims_status: 'verified'
                            }).eq('id', referenceId);
                        }
                    } catch (dbError) {
                        console.error('[eTIMS] Persistence Error:', dbError);
                        // We still return the success response as the eTIMS part "worked"
                    }
                }

                resolve(response);
            }, 1500);
        });
    }

    /**
     * Check connection status
     */
    async checkStatus(): Promise<boolean> {
        // Simulate checking if the KRA server is reachable
        return true;
    }
}

export const etimsService = new ETimsService();
