begin;

create table iam.invitations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete cascade, email citext not null, token_hash text not null unique, status text not null default 'pending' check (status in ('pending','accepted','revoked','expired')), expires_at timestamptz not null, invited_by uuid not null references auth.users(id) on delete restrict, accepted_by uuid references auth.users(id) on delete set null, accepted_at timestamptz, created_at timestamptz not null default now(), unique (organization_id, id));
create table iam.invitation_company_assignments (organization_id uuid not null references platform.organizations(id) on delete cascade, invitation_id uuid not null, company_id uuid not null references platform.companies(id) on delete cascade, primary key (invitation_id, company_id), foreign key (organization_id, invitation_id) references iam.invitations(organization_id, id) on delete cascade, foreign key (organization_id, company_id) references platform.companies(organization_id, id));
create table iam.invitation_role_assignments (organization_id uuid not null references platform.organizations(id) on delete cascade, invitation_id uuid not null, application_id uuid not null references platform.applications(id) on delete cascade, role_id uuid not null references iam.roles(id) on delete restrict, primary key (invitation_id, application_id, role_id), foreign key (organization_id, invitation_id) references iam.invitations(organization_id, id) on delete cascade);

create table real_estate.leases (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete restrict, company_id uuid not null references platform.companies(id) on delete restrict, lease_number text not null, start_date date not null, end_date date, status text not null default 'draft' check (status in ('draft','active','notice','ended','cancelled')), created_at timestamptz not null default now(), unique (organization_id, lease_number), unique (organization_id, id), check (end_date is null or end_date >= start_date));
create table real_estate.invoice_runs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete restrict, company_id uuid not null references platform.companies(id) on delete restrict, schedule_key text not null, billing_month date not null check (billing_month = date_trunc('month', billing_month)::date), idempotency_key text not null, status text not null default 'queued' check (status in ('queued','preview','approved','processing','completed','failed','cancelled')), created_at timestamptz not null default now(), unique (organization_id, company_id, schedule_key, billing_month), unique (organization_id, idempotency_key));
create table real_estate.invoices (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete restrict, company_id uuid not null references platform.companies(id) on delete restrict, lease_id uuid not null, billing_month date not null check (billing_month = date_trunc('month', billing_month)::date), total_minor bigint not null default 0 check (total_minor >= 0), status text not null default 'draft' check (status in ('draft','issued','overdue','paid','void')), created_at timestamptz not null default now(), unique (organization_id, lease_id, billing_month), unique (organization_id, id), foreign key (organization_id, company_id) references platform.companies(organization_id, id), foreign key (organization_id, lease_id) references real_estate.leases(organization_id, id));
create table real_estate.invoice_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete restrict, company_id uuid not null references platform.companies(id) on delete restrict, invoice_id uuid not null, item_type text not null, description text not null, amount_minor bigint not null check (amount_minor >= 0), created_at timestamptz not null default now(), foreign key (organization_id, invoice_id) references real_estate.invoices(organization_id, id) on delete cascade, foreign key (organization_id, company_id) references platform.companies(organization_id, id));
create table real_estate.payments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete restrict, company_id uuid not null references platform.companies(id) on delete restrict, payment_reference text not null, amount_minor bigint not null check (amount_minor > 0), status text not null default 'received' check (status in ('received','part_allocated','allocated','reversed','refunded')), paid_at timestamptz not null default now(), unique (organization_id, payment_reference), unique (organization_id, id), foreign key (organization_id, company_id) references platform.companies(organization_id, id));
create table real_estate.payment_allocations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete restrict, company_id uuid not null references platform.companies(id) on delete restrict, payment_id uuid not null, invoice_id uuid not null, amount_minor bigint not null check (amount_minor > 0), created_at timestamptz not null default now(), unique (organization_id, id), foreign key (organization_id, company_id) references platform.companies(organization_id, id), foreign key (organization_id, payment_id) references real_estate.payments(organization_id, id) on delete cascade, foreign key (organization_id, invoice_id) references real_estate.invoices(organization_id, id) on delete cascade);
create table real_estate.split_rules (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete cascade, company_id uuid not null references platform.companies(id) on delete cascade, name text not null, status text not null default 'draft' check (status in ('draft','active','retired')), unique (organization_id, company_id, name), unique (organization_id, id));
create table real_estate.split_rule_versions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete cascade, company_id uuid not null references platform.companies(id) on delete restrict, split_rule_id uuid not null, version_no integer not null, effective_from timestamptz not null, effective_until timestamptz, rule_definition jsonb not null, unique (split_rule_id, version_no), unique (organization_id, id), foreign key (organization_id, company_id) references platform.companies(organization_id, id), foreign key (organization_id, split_rule_id) references real_estate.split_rules(organization_id, id) on delete cascade, check (effective_until is null or effective_until > effective_from));
create table real_estate.split_allocations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete cascade, company_id uuid not null references platform.companies(id) on delete restrict, payment_allocation_id uuid not null, split_rule_version_id uuid not null, beneficiary_type text not null check (beneficiary_type in ('landlord','organization','supplier','tax','other')), amount_minor bigint not null check (amount_minor >= 0), status text not null default 'pending' check (status in ('pending','approved','queued','paid','failed','reversed')), foreign key (organization_id, company_id) references platform.companies(organization_id, id), foreign key (organization_id, payment_allocation_id) references real_estate.payment_allocations(organization_id, id) on delete restrict, foreign key (organization_id, split_rule_version_id) references real_estate.split_rule_versions(organization_id, id));

create table integrations.mpesa_transactions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete restrict, mpesa_account_id uuid not null references integrations.mpesa_accounts(id) on delete restrict, callback_id uuid references integrations.mpesa_callbacks(id) on delete restrict, provider_receipt text not null, transaction_type text not null check (transaction_type in ('c2b','stk','b2c','b2b','reversal','adjustment')), direction text not null check (direction in ('credit','debit')), occurred_at timestamptz not null, amount_minor bigint not null check (amount_minor > 0), status text not null check (status in ('pending','completed','failed','reversed','unknown')), raw_result jsonb not null default '{}', unique (mpesa_account_id, provider_receipt));
create table integrations.mpesa_payout_jobs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete restrict, mpesa_account_id uuid not null references integrations.mpesa_accounts(id) on delete restrict, idempotency_key text not null, beneficiary_type text not null, beneficiary_id uuid, amount_minor bigint not null check (amount_minor > 0), status text not null default 'queued' check (status in ('queued','submitted','completed','failed','unknown','reversed')), attempts integer not null default 0 check (attempts >= 0), created_at timestamptz not null default now(), unique (mpesa_account_id, idempotency_key));

alter table integrations.mpesa_accounts add constraint mpesa_accounts_org_id_key unique (organization_id, id);
alter table integrations.mpesa_callbacks add constraint mpesa_callbacks_org_id_key unique (organization_id, id);
alter table integrations.mpesa_transactions add constraint mpesa_transactions_account_org_fk foreign key (organization_id, mpesa_account_id) references integrations.mpesa_accounts(organization_id, id);
alter table integrations.mpesa_transactions add constraint mpesa_transactions_callback_org_fk foreign key (organization_id, callback_id) references integrations.mpesa_callbacks(organization_id, id);
alter table integrations.mpesa_payout_jobs add constraint mpesa_payout_account_org_fk foreign key (organization_id, mpesa_account_id) references integrations.mpesa_accounts(organization_id, id);

create table real_estate.tenants (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete restrict, company_id uuid not null references platform.companies(id) on delete restrict, full_name text not null, email citext, status text not null default 'active' check (status in ('prospect','active','former','archived')), created_at timestamptz not null default now(), unique (organization_id, id), foreign key (organization_id, company_id) references platform.companies(organization_id, id));
create table real_estate.landlords (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete restrict, company_id uuid not null references platform.companies(id) on delete restrict, full_name text not null, email citext, status text not null default 'active' check (status in ('active','inactive','archived')), created_at timestamptz not null default now(), unique (organization_id, id), foreign key (organization_id, company_id) references platform.companies(organization_id, id));
create table real_estate.caretakers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete restrict, company_id uuid not null references platform.companies(id) on delete restrict, full_name text not null, email citext, status text not null default 'active' check (status in ('active','inactive','archived')), created_at timestamptz not null default now(), unique (organization_id, id), foreign key (organization_id, company_id) references platform.companies(organization_id, id));

create table real_estate.portal_grants (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, portal_type text not null check (portal_type in ('tenant','landlord','caretaker')), entity_id uuid not null, status text not null default 'active' check (status in ('invited','active','suspended','revoked')), read_only boolean not null default false, created_at timestamptz not null default now(), unique (organization_id, user_id, portal_type, entity_id));
create table real_estate.portal_preview_sessions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete cascade, portal_type text not null check (portal_type in ('tenant','landlord','caretaker')), entity_id uuid not null, admin_user_id uuid not null references auth.users(id) on delete cascade, token_hash text not null unique, expires_at timestamptz not null, revoked_at timestamptz, created_at timestamptz not null default now());

create index payment_allocations_payment on real_estate.payment_allocations (organization_id, payment_id);
create index payment_allocations_invoice on real_estate.payment_allocations (organization_id, invoice_id);
create index split_allocations_source on real_estate.split_allocations (organization_id, payment_allocation_id);
create index portal_grants_user on real_estate.portal_grants (organization_id, user_id, status);
create index mpesa_transactions_org_time on integrations.mpesa_transactions (organization_id, occurred_at desc);

create or replace function private.assert_payment_allocation_totals() returns trigger language plpgsql set search_path = pg_catalog, real_estate as $$ declare payment_total bigint; invoice_total bigint; allocated_payment bigint; allocated_invoice bigint; begin select amount_minor into payment_total from real_estate.payments where id = new.payment_id and organization_id = new.organization_id; select total_minor into invoice_total from real_estate.invoices where id = new.invoice_id and organization_id = new.organization_id; select coalesce(sum(amount_minor),0) into allocated_payment from real_estate.payment_allocations where payment_id = new.payment_id and organization_id = new.organization_id and id <> new.id; select coalesce(sum(amount_minor),0) into allocated_invoice from real_estate.payment_allocations where invoice_id = new.invoice_id and organization_id = new.organization_id and id <> new.id; if allocated_payment + new.amount_minor > payment_total then raise exception 'payment allocation exceeds payment total'; end if; if allocated_invoice + new.amount_minor > invoice_total then raise exception 'payment allocation exceeds invoice total'; end if; return new; end; $$;
create trigger payment_allocation_totals before insert or update on real_estate.payment_allocations for each row execute function private.assert_payment_allocation_totals();

create or replace function private.assert_split_allocation_total() returns trigger language plpgsql set search_path = pg_catalog, real_estate as $$ declare source_total bigint; allocated_total bigint; begin select amount_minor into source_total from real_estate.payment_allocations where id = new.payment_allocation_id and organization_id = new.organization_id; select coalesce(sum(amount_minor),0) into allocated_total from real_estate.split_allocations where payment_allocation_id = new.payment_allocation_id and organization_id = new.organization_id and id <> new.id; if allocated_total + new.amount_minor > source_total then raise exception 'split allocation exceeds payment allocation'; end if; if new.status in ('approved','queued','paid') and allocated_total + new.amount_minor <> source_total then raise exception 'approved split allocations must balance exactly'; end if; return new; end; $$;
create trigger split_allocation_totals before insert or update on real_estate.split_allocations for each row execute function private.assert_split_allocation_total();

commit;
