begin;

create schema if not exists hr;

create table if not exists hr.departments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id), company_id uuid, code text not null, name text not null, description text, status text not null default 'active', created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, unique (organization_id, code), foreign key (organization_id, company_id) references platform.companies(organization_id,id));
alter table hr.departments add constraint departments_org_id_key unique (organization_id,id);
create table if not exists hr.designations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id), company_id uuid, department_id uuid, code text not null, name text not null, description text, grade text, status text not null default 'active', created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, unique (organization_id, code), foreign key (organization_id, company_id) references platform.companies(organization_id,id), foreign key (department_id) references hr.departments(id));
alter table hr.designations add constraint designations_org_id_key unique (organization_id,id);
create table if not exists hr.employees (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id), company_id uuid, employee_number text not null, first_name text not null, middle_name text, last_name text not null, display_name text not null, email citext, phone text, id_type text, id_number text, date_of_birth date, gender text, marital_status text, religion text, original_home text, current_residence text, department_id uuid, designation_id uuid, manager_employee_id uuid, employment_type text not null check (employment_type in ('permanent','contract','casual','intern','part_time','consultant')), employment_status text not null default 'draft' check (employment_status in ('draft','active','probation','on_leave','suspended','terminated','resigned','retired','archived')), employment_start_date date, probation_end_date date, employment_end_date date, profile_image_file_id text, profile_image_path text, profile_image_url text, pwd_status boolean not null default false, auth_user_id uuid unique references auth.users(id) on delete set null, portal_access_status text not null default 'not_invited', notes text, created_by uuid not null references auth.users(id), updated_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, archived_by uuid references auth.users(id), archive_reason text, unique (organization_id, employee_number), foreign key (organization_id,company_id) references platform.companies(organization_id,id), foreign key (organization_id,department_id) references hr.departments(organization_id,id), foreign key (organization_id,designation_id) references hr.designations(organization_id,id));
alter table hr.employees add constraint employees_org_id_key unique (organization_id,id);
alter table hr.employees add constraint employees_manager_org_fk foreign key (organization_id,manager_employee_id) references hr.employees(organization_id,id);
create table if not exists hr.employee_contacts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id), company_id uuid, employee_id uuid not null references hr.employees(id) on delete cascade, contact_type text not null check (contact_type in ('next_of_kin','emergency_contact','dependant','beneficiary')), full_name text not null, relationship text not null, phone text not null, alternative_phone text, email citext, address text, date_of_birth date, is_primary boolean not null default false, is_dependent boolean not null default false, notes text, created_by uuid not null references auth.users(id), updated_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, foreign key (organization_id,company_id) references platform.companies(organization_id,id));
create table if not exists hr.employee_statutory_details (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id), company_id uuid, employee_id uuid not null unique references hr.employees(id) on delete cascade, kra_pin text, nssf_number text, sha_number text, nhif_legacy_number text, tax_status text, created_by uuid not null references auth.users(id), updated_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, foreign key (organization_id,company_id) references platform.companies(organization_id,id));
create table if not exists hr.employee_documents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id), company_id uuid, employee_id uuid not null references hr.employees(id) on delete cascade, document_type text not null, document_number text, imagekit_file_id text not null, imagekit_file_path text not null, imagekit_url text not null, file_name text not null, mime_type text not null, file_size bigint not null, issued_at date, expires_at date, verification_status text not null default 'pending', uploaded_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, foreign key (organization_id,company_id) references platform.companies(organization_id,id));

insert into iam.permissions(permission_key, action, description) values
 ('hr.dashboard.read','read','Read HR dashboard'),('hr.employees.read','read','Read employee directory'),('hr.employees.create','create','Create employees'),('hr.employees.update','update','Update employees'),('hr.employees.archive','delete','Archive employees'),('hr.employees.reinstate','update','Reinstate employees'),('hr.contacts.read','read','Read employee contacts'),('hr.contacts.manage','manage','Manage employee contacts'),('hr.statutory.read','read','Read statutory details'),('hr.statutory.manage','manage','Manage statutory details'),('hr.documents.read','read','Read employee documents'),('hr.documents.upload','create','Upload employee documents'),('hr.documents.archive','delete','Archive employee documents'),('hr.employee_access.read','read','Read employee access'),('hr.employee_access.manage','manage','Manage employee access'),('hr.employee_invitation.send','manage','Prepare employee invitations'),('hr.audit.read','read','Read HR audit activity')
 on conflict(permission_key) do nothing;

do $$ declare t text; begin foreach t in array array['departments','designations','employees','employee_contacts','employee_statutory_details','employee_documents'] loop execute format('alter table hr.%I enable row level security',t); end loop; end $$;
create policy hr_departments_select on hr.departments for select to authenticated using (private.has_org_access(organization_id) and private.has_permission(organization_id,company_id,'hr.employees.read'));
create policy hr_designations_select on hr.designations for select to authenticated using (private.has_org_access(organization_id) and private.has_permission(organization_id,company_id,'hr.employees.read'));
create policy hr_employees_select on hr.employees for select to authenticated using (private.has_org_access(organization_id) and private.has_permission(organization_id,company_id,'hr.employees.read'));
create policy hr_employees_insert on hr.employees for insert to authenticated with check (created_by=auth.uid() and private.has_permission(organization_id,company_id,'hr.employees.create'));
create policy hr_employees_update on hr.employees for update to authenticated using (private.has_permission(organization_id,company_id,'hr.employees.update') or private.has_permission(organization_id,company_id,'hr.employees.archive')) with check (private.has_org_access(organization_id));
create policy hr_contacts_select on hr.employee_contacts for select to authenticated using (private.has_permission(organization_id,company_id,'hr.contacts.read'));
create policy hr_statutory_select on hr.employee_statutory_details for select to authenticated using (private.has_permission(organization_id,company_id,'hr.statutory.read'));
create policy hr_documents_select on hr.employee_documents for select to authenticated using (private.has_permission(organization_id,company_id,'hr.documents.read'));
create policy hr_documents_insert on hr.employee_documents for insert to authenticated with check (uploaded_by=auth.uid() and private.has_permission(organization_id,company_id,'hr.documents.upload'));

commit;
