create table if not exists platform.notifications (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references platform.organizations(id) on delete cascade, company_id uuid references platform.companies(id) on delete set null, application_id uuid references platform.applications(id) on delete set null, recipient_user_id uuid not null references auth.users(id) on delete cascade, category text not null check (category in ('system','security','access','employee','property','tenant','billing','payment','maintenance','inspection','approval','report','invitation')), severity text not null default 'info' check (severity in ('info','success','warning','error')), title text not null check (char_length(title) between 1 and 160), message text not null check (char_length(message) between 1 and 1000), action_url text, entity_type text, entity_id uuid, read_at timestamptz, dismissed_at timestamptz, created_at timestamptz not null default now(), expires_at timestamptz, metadata jsonb not null default '{}'::jsonb
);
create index if not exists notifications_recipient_created_idx on platform.notifications(recipient_user_id, created_at desc);
create table if not exists platform.notification_preferences (user_id uuid primary key references auth.users(id) on delete cascade, in_app_enabled boolean not null default true, email_enabled boolean not null default true, sms_enabled boolean not null default false, security_alerts boolean not null default true, billing_alerts boolean not null default true, approval_requests boolean not null default true, operational_alerts boolean not null default true, product_announcements boolean not null default true, updated_at timestamptz not null default now());
create table if not exists iam.role_restrictions (id uuid primary key default gen_random_uuid(), role_id uuid not null unique references iam.roles(id) on delete cascade, company_ids uuid[] not null default '{}', record_ownership_only boolean not null default false, assigned_property_ids uuid[] not null default '{}', assigned_site_ids uuid[] not null default '{}', department text, maximum_approval_amount_minor bigint, cannot_view_salary boolean not null default false, cannot_view_banking boolean not null default false, cannot_view_medical_data boolean not null default false, cannot_export boolean not null default false, cannot_delete_archive boolean not null default false, cannot_manage_users boolean not null default false, cannot_assign_roles boolean not null default false, effective_from timestamptz, expires_at timestamptz, updated_at timestamptz not null default now());
alter table iam.roles add column if not exists description text;
do $$ begin if exists (select 1 from pg_constraint where conrelid = 'iam.roles'::regclass and conname = 'roles_scope_check') then alter table iam.roles drop constraint roles_scope_check; end if; alter table iam.roles add constraint roles_scope_check check (scope in ('platform','organization','company','application','self')); exception when duplicate_object then null; end $$;
alter table platform.notifications enable row level security;
alter table platform.notification_preferences enable row level security;
alter table iam.role_restrictions enable row level security;
drop policy if exists notifications_read_self on platform.notifications;
create policy notifications_read_self on platform.notifications for select to authenticated using (recipient_user_id = auth.uid() and exists (select 1 from iam.organization_memberships m where m.organization_id = notifications.organization_id and m.user_id = auth.uid() and m.status = 'active'));
drop policy if exists notifications_update_self on platform.notifications;
create policy notifications_update_self on platform.notifications for update to authenticated using (recipient_user_id = auth.uid()) with check (recipient_user_id = auth.uid());
drop policy if exists notification_preferences_self on platform.notification_preferences;
create policy notification_preferences_self on platform.notification_preferences for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists role_restrictions_scoped on iam.role_restrictions;
create policy role_restrictions_scoped on iam.role_restrictions for select to authenticated using (exists (select 1 from iam.roles r where r.id = role_restrictions.role_id and ((r.organization_id is null and private.is_platform_operator()) or (r.organization_id is not null and private.has_org_access(r.organization_id)))));
comment on table platform.notifications is 'Persistent in-app notifications. Audit events remain separate and immutable.';
comment on table iam.role_restrictions is 'Typed role restrictions; arbitrary authorization JSON is not accepted.';
