import { createTenant, updateTenant } from "../tenant-billing";

type Initial = Record<string, string | number | null | undefined>;
type PropertyOption = { id: string; name: string; property_code?: string | null };
type UnitOption = { id: string; unit_number: string; property_id: string; property_name?: string | null; status?: string | null; monthly_rent_minor?: number | null };

export function TenantForm({ id, initial = {}, properties = [], units = [] }: { id?: string; initial?: Initial; properties?: PropertyOption[]; units?: UnitOption[] }) {
  const action = async (form: FormData) => { "use server"; await (id ? updateTenant(id, form) : createTenant(form)); };
  const value = (name: string, fallback = "") => String(initial[name] ?? fallback);
  const currentImage = value("profile_image_url");
  const initials = value("full_name", "TN").split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();

  return <form className="re-form re-tenant-form" action={action} encType="multipart/form-data">
    <div className="re-form-intro"><div><span className="re-eyebrow">Tenant profile</span><h2>{id ? "Update tenant details" : "Create a tenant profile"}</h2><p>Capture the tenant’s identity and assign them to a property unit when ready.</p></div><span className="re-form-required">* Required</span></div>

    <section className="re-form-section re-profile-section">
      <div className="re-form-section-heading"><div><span className="re-eyebrow">01 · Profile</span><h2>Identity and profile photo</h2><p>Use the tenant’s legal name and a clear profile image for quick recognition.</p></div></div>
      <div className="re-profile-upload"><div className="re-profile-photo">{currentImage ? <img src={currentImage} alt="Current tenant profile" /> : <span>{initials || "TN"}</span>}</div><label className="re-upload-box"><span className="re-upload-title">Upload profile image</span><span className="re-upload-copy">JPG, PNG or WebP · maximum 5 MB</span><input name="profile_image" type="file" accept="image/jpeg,image/png,image/webp" /></label></div>
      <div className="re-form-grid re-form-grid-wide"><label className="re-field re-field-wide"><span>Full name <b>*</b></span><input name="full_name" defaultValue={value("full_name")} placeholder="e.g. Jane Wanjiku" required /></label><label className="re-field"><span>Tenant number</span><input name="tenant_number" defaultValue={value("tenant_number")} placeholder="Generated or internal reference" /></label><label className="re-field"><span>Status</span><select name="status" defaultValue={value("status", "active")}><option value="prospect">Prospect</option><option value="active">Active</option><option value="former">Former</option></select></label></div>
    </section>

    <section className="re-form-section"><div className="re-form-section-heading"><div><span className="re-eyebrow">02 · Contact</span><h2>Contact and identification</h2><p>These details help your team identify and reach the tenant.</p></div></div><div className="re-form-grid"><label className="re-field"><span>Phone number</span><input name="phone" type="tel" defaultValue={value("phone")} placeholder="+254 7XX XXX XXX" /></label><label className="re-field"><span>Email address</span><input name="email" type="email" defaultValue={value("email")} placeholder="tenant@example.com" /></label><label className="re-field"><span>ID type</span><select name="id_type" defaultValue={value("id_type", "national_id")}><option value="national_id">National ID</option><option value="passport">Passport</option><option value="alien_id">Alien ID</option></select></label><label className="re-field"><span>ID / passport number</span><input name="national_id" defaultValue={value("national_id")} placeholder="Enter identification number" /></label><label className="re-field"><span>Date of birth</span><input name="date_of_birth" type="date" defaultValue={value("date_of_birth")} /></label><label className="re-field"><span>Gender</span><select name="gender" defaultValue={value("gender")}><option value="">Not specified</option><option>female</option><option>male</option><option>other</option></select></label></div></section>

    <section className="re-form-section"><div className="re-form-section-heading"><div><span className="re-eyebrow">03 · Assignment</span><h2>Property and unit assignment</h2><p>Select an available unit. Rent and configured deposits are inherited from the unit record.</p></div></div><div className="re-form-grid"><label className="re-field"><span>Property</span><select name="property_id" defaultValue={value("property_id")}><option value="">Select property</option>{properties.map((property) => <option key={property.id} value={property.id}>{property.name}{property.property_code ? ` (${property.property_code})` : ""}</option>)}</select></label><label className="re-field"><span>Unit</span><select name="unit_id" defaultValue={value("unit_id")}><option value="">Select unit</option>{units.filter((unit) => ["vacant", "reserved"].includes(unit.status ?? "vacant") || unit.id === value("unit_id")).map((unit) => <option key={unit.id} value={unit.id}>{unit.property_name ? `${unit.property_name} · ` : ""}{unit.unit_number} · {unit.status ?? "vacant"}{unit.monthly_rent_minor ? ` · KES ${(unit.monthly_rent_minor / 100).toLocaleString()}` : ""}</option>)}</select></label><label className="re-field"><span>Lease number</span><input name="lease_number" defaultValue={value("lease_number")} placeholder="Generated if blank" /></label><label className="re-field"><span>Lease start date</span><input name="start_date" type="date" defaultValue={value("start_date")} /></label><label className="re-field"><span>Lease end date</span><input name="end_date" type="date" defaultValue={value("end_date")} /></label></div></section>

    <section className="re-form-section"><div className="re-form-section-heading"><div><span className="re-eyebrow">04 · Emergency contact</span><h2>Emergency contact</h2><p>Keep one reliable contact on file for urgent property matters.</p></div></div><div className="re-form-grid"><label className="re-field"><span>Contact name</span><input name="emergency_contact_name" defaultValue={value("emergency_contact_name")} placeholder="Full name" /></label><label className="re-field"><span>Relationship</span><input name="emergency_contact_relationship" defaultValue={value("emergency_contact_relationship")} placeholder="e.g. Spouse, parent" /></label><label className="re-field"><span>Phone number</span><input name="emergency_contact_phone" defaultValue={value("emergency_contact_phone")} placeholder="+254 7XX XXX XXX" /></label><label className="re-field"><span>Preferred contact method</span><select name="preferred_contact_method" defaultValue={value("preferred_contact_method", "phone")}><option>phone</option><option>email</option><option>sms</option></select></label></div></section>

    <section className="re-form-section"><div className="re-form-section-heading"><div><span className="re-eyebrow">05 · Notes</span><h2>Internal notes</h2><p>Visible to your property team only.</p></div></div><label className="re-field"><span>Notes</span><textarea name="notes" defaultValue={value("notes")} placeholder="Add any helpful context about this tenant..." /></label></section>
    <div className="re-form-footer"><span>Review the information before saving.</span><button className="re-button primary" type="submit">{id ? "Save tenant" : "Create tenant"}</button></div>
  </form>;
}
