// @ts-nocheck
/**
 * Role-Aware Report Generator
 * Fetches live data from Supabase based on user role and generates
 * a well-structured CSV report with relevant summaries.
 */

import { supabase } from './supabase';

export interface ReportRow {
  [key: string]: string | number | boolean | null | undefined;
}

export interface ReportSection {
  heading: string;
  summary?: string; // A one-line summary stat
  rows: ReportRow[];
}

export interface ReportConfig {
  title: string;
  subtitle?: string;
  role?: string;
  generatedBy?: string;
  generatedAt?: string;
  sections: ReportSection[];
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function rowsToCSV(rows: ReportRow[]): string {
  if (rows.length === 0) return '"(No data available)"';
  const headers = Object.keys(rows[0]);
  const lines = [
    headers.map((h) => `"${h}"`).join(','),
    ...rows.map((row) =>
      headers
        .map((h) => {
          const val = row[h] ?? '';
          return `"${String(val).replace(/"/g, '""')}"`;
        })
        .join(',')
    ),
  ];
  return lines.join('\r\n');
}

function buildCSV(config: ReportConfig): string {
  const now = config.generatedAt ?? new Date().toLocaleString('en-KE', { timeZone: 'Africa/Nairobi' });
  const sep = '='.repeat(60);

  const lines: string[] = [
    `"${sep}"`,
    `"${config.title.toUpperCase()}"`,
    config.subtitle ? `"${config.subtitle}"` : '',
    `"Role: ${config.role ?? 'N/A'}"`,
    `"Generated by: ${config.generatedBy ?? 'Unknown'}"`,
    `"Generated at: ${now} (EAT)"`,
    `"${sep}"`,
    '',
  ];

  for (const section of config.sections) {
    lines.push(`"--- ${section.heading.toUpperCase()} ---"`);
    if (section.summary) {
      lines.push(`"Summary: ${section.summary}"`);
    }
    lines.push(rowsToCSV(section.rows));
    lines.push('');
  }

  lines.push(`"${sep}"`);
  lines.push(`"END OF REPORT"`);
  lines.push(`"${sep}"`);

  return lines.join('\r\n');
}

function downloadCSV(filename: string, content: string) {
  const BOM = '\uFEFF'; // UTF-8 BOM for Excel compatibility
  const blob = new Blob([BOM + content], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── Role-Specific Data Fetchers ──────────────────────────────────────────────

async function fetchAdminData(): Promise<ReportSection[]> {
  const [employeesRes, departmentsRes, logsRes, incidentsRes, attendanceRes, leaveRes] =
    await Promise.all([
      supabase.from('profiles').select('id, full_name, role, department, designation, employment_type, created_at').order('created_at', { ascending: false }).limit(100),
      supabase.from('departments').select('id, name, created_at').order('created_at', { ascending: false }),
      supabase.from('activity_logs').select('user_name, action_type, action_category, description, platform, created_at').order('created_at', { ascending: false }).limit(50),
      supabase.from('security_incidents').select('id, type, severity, status, reported_at').order('reported_at', { ascending: false }).limit(50),
      supabase.from('hr_attendance').select('id, employee_id, check_in_time, check_out_time, status, date').order('date', { ascending: false }).limit(50),
      supabase.from('hr_leave_requests').select('id, employee_id, leave_type_id, status, start_date, end_date').order('created_at', { ascending: false }).limit(50),
    ]);

  const employees = employeesRes.data ?? [];
  const departments = departmentsRes.data ?? [];
  const logs = logsRes.data ?? [];
  const incidents = incidentsRes.data ?? [];
  const attendance = attendanceRes.data ?? [];
  const leave = leaveRes.data ?? [];

  // Role breakdown summary
  const roleCounts: Record<string, number> = {};
  employees.forEach((e: any) => {
    roleCounts[e.role] = (roleCounts[e.role] ?? 0) + 1;
  });

  return [
    {
      heading: 'Staff Overview',
      summary: `Total: ${employees.length} employees across ${departments.length} departments`,
      rows: employees.map((e: any) => ({
        Name: e.full_name ?? '',
        Role: e.role ?? '',
        Department: e.department ?? '',
        Designation: e.designation ?? '',
        'Employment Type': e.employment_type ?? '',
        'Joined': e.created_at ? new Date(e.created_at).toLocaleDateString('en-KE') : '',
      })),
    },
    {
      heading: 'Role Distribution',
      summary: Object.entries(roleCounts).map(([r, c]) => `${r}: ${c}`).join(' | '),
      rows: Object.entries(roleCounts).map(([Role, Count]) => ({ Role, Count })),
    },
    {
      heading: 'Departments',
      summary: `${departments.length} departments configured`,
      rows: departments.map((d: any) => ({
        Department: d.name ?? '',
        Created: d.created_at ? new Date(d.created_at).toLocaleDateString('en-KE') : '',
      })),
    },
    {
      heading: 'Recent System Activity',
      summary: `${logs.length} recent log entries`,
      rows: logs.map((l: any) => ({
        User: l.user_name ?? '',
        Action: l.action_type ?? '',
        Category: l.action_category ?? '',
        Description: l.description ?? '',
        Platform: l.platform ?? '',
        'Date/Time': l.created_at ? new Date(l.created_at).toLocaleString('en-KE') : '',
      })),
    },
    {
      heading: 'Recent Security Incidents',
      summary: `${incidents.filter((i: any) => i.status === 'open').length} open incidents`,
      rows: incidents.map((i: any) => ({
        Type: i.type ?? '',
        Severity: i.severity ?? '',
        Status: i.status ?? '',
        Reported: i.reported_at ? new Date(i.reported_at).toLocaleString('en-KE') : '',
      })),
    },
    {
      heading: 'Attendance Summary',
      summary: `${attendance.filter((a: any) => a.status === 'present').length} present out of ${attendance.length}`,
      rows: attendance.slice(0, 30).map((a: any) => ({
        Date: a.date ?? '',
        Status: a.status ?? '',
        'Clock In': a.check_in_time ? new Date(`1970-01-01T${a.check_in_time}`).toLocaleTimeString('en-KE') : '',
        'Clock Out': a.check_out_time ? new Date(`1970-01-01T${a.check_out_time}`).toLocaleTimeString('en-KE') : '',
      })),
    },
    {
      heading: 'Leave Requests',
      summary: `${leave.filter((l: any) => l.status === 'pending').length} pending approvals`,
      rows: leave.map((l: any) => ({
        'Leave Type ID': l.leave_type_id ?? '',
        'Start Date': l.start_date ?? '',
        'End Date': l.end_date ?? '',
        Status: l.status ?? '',
      })),
    },
  ];
}

async function fetchHRData(): Promise<ReportSection[]> {
  const [employeesRes, leaveRes, attendanceRes, complaintsRes] = await Promise.all([
    supabase.from('profiles').select('id, full_name, role, department, designation, employment_type, phone').order('full_name'),
    supabase.from('hr_leave_requests').select('id, employee_id, leave_type_id, status, start_date, end_date, created_at').order('created_at', { ascending: false }).limit(100),
    supabase.from('hr_attendance').select('id, employee_id, status, date').order('date', { ascending: false }).limit(100),
    supabase.from('hr_complaints').select('id, subject, status, created_at').order('created_at', { ascending: false }).limit(50),
  ]);

  const employees = employeesRes.data ?? [];
  const leave = leaveRes.data ?? [];
  const attendance = attendanceRes.data ?? [];
  const complaints = complaintsRes.data ?? [];

  return [
    {
      heading: 'Employee Directory',
      summary: `${employees.length} total employees`,
      rows: employees.map((e: any) => ({
        Name: e.full_name ?? '',
        Role: e.role ?? '',
        Department: e.department ?? '',
        Designation: e.designation ?? '',
        Phone: e.phone ?? '',
      })),
    },
    {
      heading: 'Leave Requests',
      summary: `${leave.filter((l: any) => l.status === 'pending').length} pending, ${leave.filter((l: any) => l.status === 'approved').length} approved`,
      rows: leave.map((l: any) => ({
        'Leave Type ID': l.leave_type_id ?? '',
        Status: l.status ?? '',
        'Start Date': l.start_date ?? '',
        'End Date': l.end_date ?? '',
        'Applied On': l.created_at ? new Date(l.created_at).toLocaleDateString('en-KE') : '',
      })),
    },
    {
      heading: 'Attendance Records',
      summary: `${attendance.filter((a: any) => a.status === 'present').length} present, ${attendance.filter((a: any) => a.status === 'absent').length} absent (last 100 records)`,
      rows: attendance.map((a: any) => ({
        Date: a.date ?? '',
        Status: a.status ?? '',
      })),
    },
    {
      heading: 'Complaints',
      summary: `${complaints.filter((c: any) => c.status === 'open').length} open complaints`,
      rows: complaints.map((c: any) => ({
        Subject: c.subject ?? '',
        Status: c.status ?? '',
        Raised: c.created_at ? new Date(c.created_at).toLocaleDateString('en-KE') : '',
      })),
    },
  ];
}

async function fetchSecurityData(): Promise<ReportSection[]> {
  const [incidentsRes, patrolsRes, guardsRes, sitesRes, visitorsRes] = await Promise.all([
    supabase.from('security_incidents').select('id, type, severity, status, location, description, reported_at').order('reported_at', { ascending: false }).limit(100),
    supabase.from('security_patrol_logs').select('id, status, scanned_at').order('scanned_at', { ascending: false }).limit(100),
    supabase.from('profiles').select('id, full_name, phone, department').ilike('role', '%guard%').order('full_name'),
    supabase.from('security_sites').select('id, name, location, status').order('name'),
    supabase.from('sec_visitor_logs').select('id, purpose_of_visit, status, created_at').order('created_at', { ascending: false }).limit(50),
  ]);

  const incidents = incidentsRes.data ?? [];
  const patrols = patrolsRes.data ?? [];
  const guards = guardsRes.data ?? [];
  const sites = sitesRes.data ?? [];
  const visitors = visitorsRes.data ?? [];

  return [
    {
      heading: 'Security Incidents',
      summary: `${incidents.filter((i: any) => i.status === 'open').length} open, ${incidents.filter((i: any) => i.severity === 'critical').length} critical`,
      rows: incidents.map((i: any) => ({
        Type: i.type ?? '',
        Severity: i.severity ?? '',
        Status: i.status ?? '',
        Location: i.location ?? '',
        Description: (i.description ?? '').substring(0, 80),
        Reported: i.reported_at ? new Date(i.reported_at).toLocaleString('en-KE') : '',
      })),
    },
    {
      heading: 'Patrol Logs',
      summary: `${patrols.length} patrol checkpoints logged`,
      rows: patrols.map((p: any) => ({
        Status: p.status ?? '',
        'Date/Time': p.scanned_at ? new Date(p.scanned_at).toLocaleString('en-KE') : '',
      })),
    },
    {
      heading: 'Guards on Roster',
      summary: `${guards.length} guards`,
      rows: guards.map((g: any) => ({
        Name: g.full_name ?? '',
        Phone: g.phone ?? '',
        Department: g.department ?? '',
      })),
    },
    {
      heading: 'Sites',
      summary: `${sites.length} sites`,
      rows: sites.map((s: any) => ({
        Site: s.name ?? '',
        Location: s.location ?? '',
        Status: s.status ?? '',
      })),
    },
    {
      heading: 'Visitor Logs',
      summary: `${visitors.filter((v: any) => v.status === 'checked_in').length} currently checked in`,
      rows: visitors.map((v: any) => ({
        Purpose: v.purpose_of_visit ?? '',
        Status: v.status ?? '',
        'Date/Time': v.created_at ? new Date(v.created_at).toLocaleString('en-KE') : '',
      })),
    },
  ];
}

async function fetchRealEstateData(): Promise<ReportSection[]> {
  const [propertiesRes, tenantsRes, leasesRes, maintenanceRes, paymentsRes] = await Promise.all([
    supabase.from('re_properties').select('id, name, address, property_type, total_units, status').order('name'),
    supabase.from('profiles').select('id, full_name, phone, email').ilike('role', '%tenant%').order('full_name'),
    supabase.from('re_leases').select('id, start_date, end_date, monthly_rent, status').order('start_date', { ascending: false }).limit(50),
    supabase.from('re_maintenance_requests').select('id, category, priority, status, created_at').order('created_at', { ascending: false }).limit(50),
    supabase.from('re_payments').select('id, amount, due_date, payment_date, status').order('due_date', { ascending: false }).limit(50),
  ]);

  const properties = propertiesRes.data ?? [];
  const tenants = tenantsRes.data ?? [];
  const leases = leasesRes.data ?? [];
  const maintenance = maintenanceRes.data ?? [];
  const payments = paymentsRes.data ?? [];

  return [
    {
      heading: 'Properties',
      summary: `${properties.length} properties, ${properties.filter((p: any) => p.status === 'active').length} active`,
      rows: properties.map((p: any) => ({
        Name: p.name ?? '',
        Address: p.address ?? '',
        Type: p.property_type ?? '',
        'Total Units': p.total_units ?? '',
        Status: p.status ?? '',
      })),
    },
    {
      heading: 'Tenants',
      summary: `${tenants.length} registered tenants`,
      rows: tenants.map((t: any) => ({
        Name: t.full_name ?? '',
        Phone: t.phone ?? '',
        Email: t.email ?? '',
      })),
    },
    {
      heading: 'Active Leases',
      summary: `${leases.filter((l: any) => l.status === 'active').length} active leases`,
      rows: leases.map((l: any) => ({
        'Start Date': l.start_date ?? '',
        'End Date': l.end_date ?? '',
        'Monthly Rent (KES)': l.monthly_rent ?? '',
        Status: l.status ?? '',
      })),
    },
    {
      heading: 'Maintenance Requests',
      summary: `${maintenance.filter((m: any) => m.status === 'open').length} open requests`,
      rows: maintenance.map((m: any) => ({
        Category: m.category ?? '',
        Priority: m.priority ?? '',
        Status: m.status ?? '',
        'Raised On': m.created_at ? new Date(m.created_at).toLocaleDateString('en-KE') : '',
      })),
    },
    {
      heading: 'Rent Payments',
      summary: `KES ${payments.filter((p: any) => p.status === 'paid').reduce((sum: number, p: any) => sum + (p.amount ?? 0), 0).toLocaleString()} collected`,
      rows: payments.map((p: any) => ({
        'Amount (KES)': p.amount ?? '',
        'Due Date': p.due_date ?? '',
        'Paid Date': p.payment_date ?? '',
        Status: p.status ?? '',
      })),
    },
  ];
}

async function fetchStaffData(userId: string): Promise<ReportSection[]> {
  const [profileRes, leaveRes, attendanceRes, payslipRes] = await Promise.all([
    supabase.from('profiles').select('*').eq('id', userId).single(),
    supabase.from('hr_leave_requests').select('leave_type_id, status, start_date, end_date, created_at').eq('employee_id', userId).order('created_at', { ascending: false }),
    supabase.from('hr_attendance').select('date, status, check_in_time, check_out_time').eq('employee_id', userId).order('date', { ascending: false }).limit(30),
    supabase.from('payslips').select('month, year, gross_salary, total_deductions, net_salary, status').eq('employee_id', userId).order('year', { ascending: false }).order('month', { ascending: false }).limit(12),
  ]);

  const profile = profileRes.data;
  const leave = leaveRes.data ?? [];
  const attendance = attendanceRes.data ?? [];
  const payslips = payslipRes.data ?? [];

  return [
    {
      heading: 'My Profile Summary',
      summary: `${profile?.full_name ?? ''} | ${profile?.role ?? ''} | ${profile?.department ?? ''}`,
      rows: profile ? [
        { Field: 'Full Name', Value: profile.full_name ?? '' },
        { Field: 'Email', Value: profile.email ?? '' },
        { Field: 'Role', Value: profile.role ?? '' },
        { Field: 'Department', Value: profile.department ?? '' },
        { Field: 'Designation', Value: profile.designation ?? '' },
        { Field: 'Phone', Value: profile.phone ?? '' },
        { Field: 'Employment Type', Value: profile.employment_type ?? '' },
      ] : [],
    },
    {
      heading: 'My Leave History',
      summary: `${leave.filter(l => l.status === 'approved').length} approved, ${leave.filter(l => l.status === 'pending').length} pending`,
      rows: leave.map((l: any) => ({
        'Leave Type ID': l.leave_type_id ?? '',
        Status: l.status ?? '',
        'Start Date': l.start_date ?? '',
        'End Date': l.end_date ?? '',
        'Applied On': l.created_at ? new Date(l.created_at).toLocaleDateString('en-KE') : '',
      })),
    },
    {
      heading: 'My Attendance (Last 30 Days)',
      summary: `${attendance.filter(a => a.status === 'present').length} days present`,
      rows: attendance.map((a: any) => ({
        Date: a.date ?? '',
        Status: a.status ?? '',
        'Clock In': a.check_in_time ? new Date(`1970-01-01T${a.check_in_time}`).toLocaleTimeString('en-KE') : '',
        'Clock Out': a.check_out_time ? new Date(`1970-01-01T${a.check_out_time}`).toLocaleTimeString('en-KE') : '',
      })),
    },
    {
      heading: 'My Payslips',
      summary: payslips.length > 0 ? `Last pay: KES ${payslips[0]?.net_salary?.toLocaleString() ?? 0}` : 'No payslips found',
      rows: payslips.map((p: any) => ({
        Month: `${p.month}/${p.year}`,
        'Gross (KES)': p.gross_salary ?? '',
        'Deductions (KES)': p.total_deductions ?? '',
        'Net Pay (KES)': p.net_salary ?? '',
        Status: p.status ?? '',
      })),
    },
  ];
}

// ─── Main Export ──────────────────────────────────────────────────────────────

export async function generateRoleReport(
  profile: { id: string; full_name: string; email: string; role: string } | null
): Promise<void> {
  if (!profile) return;

  const role = (profile.role ?? '').toLowerCase();
  const now = new Date().toLocaleString('en-KE', { timeZone: 'Africa/Nairobi' });
  let title = 'HAKIKA Operations Report';
  let sections: ReportSection[] = [];

  const isAdmin = ['super admin', 'director', 'director / super admin', 'administrator', 'admin'].includes(role);
  const isHR = role.includes('hr') || role === 'hr manager';
  const isSecurity = role.includes('security') || role === 'guard' || role.includes('security supervisor');
  const isRealEstate = role.includes('property') || role === 'landlord' || role === 'tenant';

  if (isAdmin) {
    title = 'HAKIKA System-Wide Admin Report';
    sections = await fetchAdminData();
  } else if (isHR) {
    title = 'HAKIKA HR Department Report';
    sections = await fetchHRData();
  } else if (isSecurity) {
    title = 'HAKIKA Security Operations Report';
    sections = await fetchSecurityData();
  } else if (isRealEstate) {
    title = 'HAKIKA Real Estate Report';
    sections = await fetchRealEstateData();
  } else {
    // Staff / Employee — show personal summary
    title = 'My HAKIKA Profile Report';
    sections = await fetchStaffData(profile.id);
  }

  const config: ReportConfig = {
    title,
    subtitle: `Role: ${profile.role}`,
    role: profile.role,
    generatedBy: `${profile.full_name} (${profile.email})`,
    generatedAt: now,
    sections,
  };

  const csv = buildCSV(config);
  const slug = title.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
  const date = new Date().toISOString().split('T')[0];
  const BOM = '\uFEFF';
  const blob = new Blob([BOM + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${slug}_${date}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Legacy simple report - kept for backward compatibility */
export function generateCSVReport(config: {
  title: string;
  subtitle?: string;
  sections: { heading: string; rows: ReportRow[] }[];
  generatedBy?: string;
}): void {
  const now = new Date().toLocaleString('en-KE', { timeZone: 'Africa/Nairobi' });
  const sep = '='.repeat(60);
  const lines: string[] = [
    `"${sep}"`,
    `"${config.title.toUpperCase()}"`,
    config.subtitle ? `"${config.subtitle}"` : '',
    `"Generated at: ${now} (EAT)"`,
    config.generatedBy ? `"By: ${config.generatedBy}"` : '',
    `"${sep}"`,
    '',
  ];
  for (const section of config.sections) {
    lines.push(`"--- ${section.heading.toUpperCase()} ---"`);
    lines.push(rowsToCSV(section.rows));
    lines.push('');
  }
  lines.push(`"END OF REPORT"`);

  const csv = lines.join('\r\n');
  const BOM = '\uFEFF';
  const blob = new Blob([BOM + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const slug = config.title.toLowerCase().replace(/\s+/g, '_');
  const date = new Date().toISOString().split('T')[0];
  a.download = `${slug}_${date}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
