import "server-only";
import { redirect } from "next/navigation";
import { requireApplicationContext, requireMutationContext } from "@/lib/platform/context";
import { recordRealEstateAudit } from "./services/audit";

async function setup(permission: string) { return requireMutationContext("REAL_ESTATE", permission); }
const text = (v: FormDataEntryValue | null) => String(v ?? "").trim();
const minor = (v: FormDataEntryValue | null) => Math.max(0, Math.round(Number(v ?? 0) * 100));
const storedMinor = (value: unknown) => Math.max(0, Math.round(Number(value ?? 0) * 100));

async function uploadTenantProfileImage(ctx: any, tenantId: string, form: FormData) {
  const file = form.get("profile_image");
  if (!(file instanceof File) || file.size === 0) return null;
  if (!file.type.startsWith("image/") || file.size > 5 * 1024 * 1024) return { error: "Profile image must be an image smaller than 5 MB" };
  const extension = file.name.split(".").pop()?.toLowerCase() || "jpg";
  const path = `${ctx.organizationId}/${tenantId}/profile-${Date.now()}.${extension}`;
  const { error } = await ctx.supabase.storage.from("tenant-avatars").upload(path, file, { contentType: file.type, cacheControl: "3600", upsert: true });
  if (error) return { error: `Could not upload profile image: ${error.message}` };
  return { url: ctx.supabase.storage.from("tenant-avatars").getPublicUrl(path).data.publicUrl };
}

async function resolveAssignment(ctx: any, propertyId: string, unitId: string) {
  if (!propertyId && !unitId) return { unit: null as any };
  if (!propertyId || !unitId) return { error: "Select both a property and a unit to assign the tenant" };
  let query = ctx.supabase.schema("real_estate").from("units").select("id,property_id,status,monthly_rent_minor,unit_number,rent_deposit_amount,water_bill_amount,electricity_bill_amount,unit_config").eq("id", unitId).eq("organization_id", ctx.organizationId).is("archived_at", null);
  if (ctx.companyId) query = query.eq("company_id", ctx.companyId);
  const { data: unit, error } = await query.maybeSingle();
  if (error || !unit) return { error: "The selected unit could not be found" };
  if (unit.property_id !== propertyId) return { error: "The selected unit does not belong to that property" };
  if (!["vacant", "reserved"].includes(unit.status) && unit.status !== "occupied") return { error: "Only vacant or reserved units can be assigned" };
  return { unit };
}

async function syncAssignment(ctx: any, tenantId: string, form: FormData) {
  const propertyId = text(form.get("property_id")), unitId = text(form.get("unit_id"));
  const assignment = await resolveAssignment(ctx, propertyId, unitId);
  if (assignment.error || !assignment.unit) return assignment.error ? { error: assignment.error } : null;
  const leaseNumber = text(form.get("lease_number")) || `LEASE-${Date.now().toString(36).toUpperCase()}`;
  const unitConfig = assignment.unit.unit_config || {};
  const leasePayload = { organization_id: ctx.organizationId, company_id: ctx.companyId, tenant_id: tenantId, property_id: propertyId, unit_id: unitId, lease_number: leaseNumber, start_date: text(form.get("start_date")) || new Date().toISOString().slice(0, 10), end_date: text(form.get("end_date")) || null, status: "active", rent_amount_minor: assignment.unit.monthly_rent_minor || 0, currency: "KES", deposit_amount_minor: storedMinor(assignment.unit.rent_deposit_amount ?? unitConfig.rent_deposit_amount), water_deposit_amount_minor: storedMinor(assignment.unit.water_bill_amount ?? unitConfig.water_bill_amount), electricity_deposit_amount_minor: storedMinor(assignment.unit.electricity_bill_amount ?? unitConfig.electricity_bill_amount), activated_at: new Date().toISOString(), updated_by: ctx.userId, created_by: ctx.userId };
  let existing = ctx.supabase.schema("real_estate").from("leases").select("id,unit_id").eq("tenant_id", tenantId).eq("organization_id", ctx.organizationId).eq("status", "active").is("archived_at", null);
  if (ctx.companyId) existing = existing.eq("company_id", ctx.companyId);
  const { data: current } = await existing.maybeSingle();
  const result = current ? await ctx.supabase.schema("real_estate").from("leases").update(leasePayload).eq("id", current.id) : await ctx.supabase.schema("real_estate").from("leases").insert(leasePayload).select("id").single();
  if (result.error) return { error: result.error.message };
  if (current?.unit_id && current.unit_id !== unitId) await ctx.supabase.schema("real_estate").from("units").update({ status: "vacant", updated_at: new Date().toISOString() }).eq("id", current.unit_id).eq("organization_id", ctx.organizationId);
  const unitUpdate = await ctx.supabase.schema("real_estate").from("units").update({ status: "occupied", updated_at: new Date().toISOString() }).eq("id", unitId).eq("organization_id", ctx.organizationId);
  if (unitUpdate.error) return { error: unitUpdate.error.message };
  return null;
}

export async function createTenant(form: FormData) { const ctx = await setup("real_estate.tenants.create"); const full_name = text(form.get("full_name")); if (!full_name) return { error: "Full name is required" }; const assignment = await resolveAssignment(ctx, text(form.get("property_id")), text(form.get("unit_id"))); if (assignment.error) return { error: assignment.error }; const payload = { organization_id: ctx.organizationId, company_id: ctx.companyId, full_name, tenant_number: text(form.get("tenant_number")) || null, email: text(form.get("email")).toLowerCase() || null, phone: text(form.get("phone")) || null, id_type: text(form.get("id_type")) || null, national_id: text(form.get("national_id")) || null, date_of_birth: text(form.get("date_of_birth")) || null, gender: text(form.get("gender")) || null, emergency_contact_name: text(form.get("emergency_contact_name")) || null, emergency_contact_phone: text(form.get("emergency_contact_phone")) || null, emergency_contact_relationship: text(form.get("emergency_contact_relationship")) || null, preferred_contact_method: text(form.get("preferred_contact_method")) || null, status: text(form.get("status")) || "active", notes: text(form.get("notes")) || null, created_by: ctx.userId }; const { data, error } = await ctx.supabase.schema("real_estate").from("tenants").insert(payload).select("id").single(); if (error || !data) return { error: error?.message ?? "Could not create tenant" }; const image = await uploadTenantProfileImage(ctx, data.id, form); if (image?.error) return image; if (image?.url) { const imageUpdate = await ctx.supabase.schema("real_estate").from("tenants").update({ profile_image_url: image.url, updated_by: ctx.userId }).eq("id", data.id); if (imageUpdate.error) return { error: imageUpdate.error.message }; } const assignmentError = await syncAssignment(ctx, data.id, form); if (assignmentError?.error) return assignmentError; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "tenant.created", entityType: "tenant", entityId: data.id, label: full_name }); redirect(`/real-estate/tenants/${data.id}`); }
export async function updateTenant(id: string, form: FormData) { const ctx = await setup("real_estate.tenants.update"); const full_name = text(form.get("full_name")); if (!full_name) return { error: "Full name is required" }; let q = ctx.supabase.schema("real_estate").from("tenants").update({ full_name, tenant_number: text(form.get("tenant_number")) || null, email: text(form.get("email")).toLowerCase() || null, phone: text(form.get("phone")) || null, id_type: text(form.get("id_type")) || null, national_id: text(form.get("national_id")) || null, date_of_birth: text(form.get("date_of_birth")) || null, gender: text(form.get("gender")) || null, emergency_contact_name: text(form.get("emergency_contact_name")) || null, emergency_contact_phone: text(form.get("emergency_contact_phone")) || null, emergency_contact_relationship: text(form.get("emergency_contact_relationship")) || null, preferred_contact_method: text(form.get("preferred_contact_method")) || null, status: text(form.get("status")) || "active", notes: text(form.get("notes")) || null, updated_by: ctx.userId }).eq("id", id).eq("organization_id", ctx.organizationId).is("archived_at", null); if (ctx.companyId) q = q.eq("company_id", ctx.companyId); const { error } = await q; if (error) return { error: error.message }; const image = await uploadTenantProfileImage(ctx, id, form); if (image?.error) return image; if (image?.url) { const imageUpdate = await ctx.supabase.schema("real_estate").from("tenants").update({ profile_image_url: image.url, updated_by: ctx.userId }).eq("id", id); if (imageUpdate.error) return { error: imageUpdate.error.message }; } const assignmentError = await syncAssignment(ctx, id, form); if (assignmentError?.error) return assignmentError; redirect(`/real-estate/tenants/${id}`); }
export async function archiveTenant(id: string) { const ctx = await setup("real_estate.tenants.archive"); let q = ctx.supabase.schema("real_estate").from("tenants").update({ archived_at: new Date().toISOString(), archived_by: ctx.userId, status: "archived" }).eq("id", id).eq("organization_id", ctx.organizationId).is("archived_at", null); if (ctx.companyId) q = q.eq("company_id", ctx.companyId); const { error } = await q; if (error) return { error: error.message }; redirect("/real-estate/tenants"); }
export async function createLease(form: FormData) { const ctx = await setup("real_estate.leases.create"); const tenant_id = text(form.get("tenant_id")), unit_id = text(form.get("unit_id")), lease_number = text(form.get("lease_number")); if (!tenant_id || !unit_id || !lease_number) return { error: "Tenant, unit and lease number are required" }; const { data, error } = await ctx.supabase.schema("real_estate").from("leases").insert({ organization_id: ctx.organizationId, company_id: ctx.companyId, tenant_id, unit_id, lease_number, start_date: text(form.get("start_date")), end_date: text(form.get("end_date")) || null, status: "draft", rent_amount_minor: Math.round(Number(form.get("rent_amount") ?? 0) * 100), currency: text(form.get("currency")) || "KES", created_by: ctx.userId }).select("id").single(); if (error || !data) return { error: error?.message ?? "Could not create lease" }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "lease.created", entityType: "lease", entityId: data.id, label: lease_number }); redirect(`/real-estate/leases/${data.id}`); }
export async function createInvoice(form: FormData) { const ctx = await setup("real_estate.invoices.create"); const lease_id = text(form.get("lease_id")); if (!lease_id) return { error: "Select a lease" }; const total = Math.round(Number(form.get("total") ?? 0) * 100); if (total <= 0) return { error: "Invoice total must be greater than zero" }; const { data, error } = await ctx.supabase.schema("real_estate").from("invoices").insert({ organization_id: ctx.organizationId, company_id: ctx.companyId, lease_id, billing_month: `${text(form.get("billing_month"))}-01`, total_minor: total, subtotal_minor: total, balance_due_minor: total, status: "draft", created_by: ctx.userId }).select("id").single(); if (error || !data) return { error: error?.message ?? "Could not create invoice" }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "invoice.created", entityType: "invoice", entityId: data.id }); redirect(`/real-estate/invoices/${data.id}`); }
export async function createPayment(form: FormData) { const ctx = await setup("real_estate.payments.record"); const amount = Math.round(Number(form.get("amount") ?? 0) * 100), reference = text(form.get("reference")); if (amount <= 0 || !reference) return { error: "Amount and payment reference are required" }; const { data, error } = await ctx.supabase.schema("real_estate").from("payments").insert({ organization_id: ctx.organizationId, company_id: ctx.companyId, tenant_id: text(form.get("tenant_id")) || null, payment_reference: reference, provider_reference: text(form.get("provider_reference")) || null, amount_minor: amount, unallocated_amount_minor: amount, payment_method: text(form.get("payment_method")) || "other", paid_at: text(form.get("paid_at")) || new Date().toISOString(), status: "received", recorded_by: ctx.userId }).select("id").single(); if (error || !data) return { error: error?.code === "23505" ? "That payment reference already exists" : error?.message ?? "Could not record payment" }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "payment.recorded", entityType: "payment", entityId: data.id, label: reference }); redirect(`/real-estate/payments/${data.id}`); }
export async function swapTenantUnit(form: FormData) { const ctx = await setup("real_estate.leases.update"); const tenantId = text(form.get("tenant_id")), toPropertyId = text(form.get("to_property_id")), toUnitId = text(form.get("to_unit_id")), effectiveDate = text(form.get("effective_date")); if (!tenantId || !toPropertyId || !toUnitId || !effectiveDate) return { error: "Tenant, destination property, unit and effective date are required" }; const leaseQuery = ctx.supabase.schema("real_estate").from("leases").select("id,property_id,unit_id,company_id").eq("tenant_id", tenantId).eq("organization_id", ctx.organizationId).eq("status", "active").is("archived_at", null).maybeSingle(); const { data: lease, error: leaseError } = await leaseQuery; if (leaseError || !lease) return { error: "No active lease was found for this tenant" }; let unitQuery = ctx.supabase.schema("real_estate").from("units").select("id,property_id,status,company_id").eq("id", toUnitId).eq("property_id", toPropertyId).eq("organization_id", ctx.organizationId).is("archived_at", null); if (ctx.companyId) unitQuery = unitQuery.eq("company_id", ctx.companyId); const { data: destination, error: destinationError } = await unitQuery.maybeSingle(); if (destinationError || !destination) return { error: "The destination unit could not be found" }; if (destination.status !== "vacant" && destination.status !== "reserved") return { error: "The destination unit is not available" }; const transfer = await ctx.supabase.schema("real_estate").from("tenant_unit_transfers").insert({ organization_id: ctx.organizationId, company_id: ctx.companyId ?? lease.company_id, tenant_id: tenantId, lease_id: lease.id, from_property_id: lease.property_id, from_unit_id: lease.unit_id, to_property_id: toPropertyId, to_unit_id: toUnitId, balance_handling: text(form.get("balance_handling")) || "with_balance", effective_date: effectiveDate, reason: text(form.get("reason")) || null, created_by: ctx.userId }).select("id").single(); if (transfer.error) return { error: transfer.error.message }; const updateLease = await ctx.supabase.schema("real_estate").from("leases").update({ property_id: toPropertyId, unit_id: toUnitId, updated_by: ctx.userId, updated_at: new Date().toISOString() }).eq("id", lease.id).eq("organization_id", ctx.organizationId); if (updateLease.error) return { error: updateLease.error.message }; if (lease.unit_id) await ctx.supabase.schema("real_estate").from("units").update({ status: "vacant", updated_at: new Date().toISOString() }).eq("id", lease.unit_id).eq("organization_id", ctx.organizationId); const updateUnit = await ctx.supabase.schema("real_estate").from("units").update({ status: "occupied", updated_at: new Date().toISOString() }).eq("id", toUnitId).eq("organization_id", ctx.organizationId); if (updateUnit.error) return { error: updateUnit.error.message }; return { success: true, transferId: transfer.data?.id }; }
export async function allocatePayment(form: FormData) { const ctx = await setup("real_estate.payments.allocate"); const payment_id = text(form.get("payment_id")), invoice_id = text(form.get("invoice_id")), amount_minor = Math.round(Number(form.get("amount") ?? 0) * 100); if (!payment_id || !invoice_id || amount_minor <= 0) return { error: "Payment, invoice and allocation amount are required" }; const { error } = await ctx.supabase.schema("real_estate").from("payment_allocations").insert({ organization_id: ctx.organizationId, company_id: ctx.companyId, payment_id, invoice_id, amount_minor }); if (error) return { error: error.message }; redirect("/real-estate/payments/allocation"); }

export async function getScopedTenant(id: string) { const ctx = await requireApplicationContext("REAL_ESTATE"); let q = ctx.supabase.schema("real_estate").from("tenants").select("*").eq("id", id).eq("organization_id", ctx.organizationId).is("archived_at", null); if (ctx.companyId) q = q.eq("company_id", ctx.companyId); return q.maybeSingle(); }
export async function listScopedTenants(search = "") { const ctx = await requireApplicationContext("REAL_ESTATE"); let q = ctx.supabase.schema("real_estate").from("tenants").select("*", { count: "exact" }).eq("organization_id", ctx.organizationId).is("archived_at", null).order("created_at", { ascending: false }); if (ctx.companyId) q = q.eq("company_id", ctx.companyId); if (search) { const escaped = search.replace(/[%(),]/g, ""); q = q.or(`full_name.ilike.%${escaped}%,email.ilike.%${escaped}%,phone.ilike.%${escaped}%,tenant_number.ilike.%${escaped}%,national_id.ilike.%${escaped}%`); } return q; }
export async function getTenantContext() { return requireApplicationContext("REAL_ESTATE"); }
export async function getAuthenticatedTenant() { const ctx = await requireApplicationContext("REAL_ESTATE"); const { data } = await ctx.supabase.schema("real_estate").from("tenants").select("*").eq("organization_id", ctx.organizationId).eq("auth_user_id", ctx.userId).is("archived_at", null).maybeSingle(); return { ctx, tenant: data }; }
