"use server";
import { redirect } from "next/navigation";
import { requireMutationContext } from "@/lib/platform/context";
import { validateProperty, validateUnit, validateAsset, type PropertyInput, type UnitInput, type AssetInput } from "../schemas";
import { insertProperty, updateProperty, insertUnit, updateUnit, insertAsset } from "../repositories";
import { recordRealEstateAudit } from "../services/audit";

async function setup(permission: string) { return requireMutationContext("REAL_ESTATE", permission); }
function propertyCodeBase(name: string) { const words = name.normalize("NFKD").replace(/[^a-zA-Z0-9\s-]/g, " ").trim().split(/[\s-]+/).filter(Boolean); const base = words.length > 1 ? words.map((word) => word[0]).join("") : (words[0] ?? "PROPERTY"); return base.toUpperCase().slice(0, 8) || "PROPERTY"; }
async function generatePropertyCode(ctx: Awaited<ReturnType<typeof setup>>, name: string): Promise<{ code?: string; error?: string }> { const base = propertyCodeBase(name); let query = ctx.supabase.schema("real_estate").from("properties").select("property_code").eq("organization_id", ctx.organizationId).ilike("property_code", base + "%"); query = ctx.companyId ? query.eq("company_id", ctx.companyId) : query.is("company_id", null); const { data, error } = await query.limit(100); if (error) return { error: "Could not generate a property code" }; const used = new Set((data ?? []).map((row) => String(row.property_code).toUpperCase())); if (!used.has(base)) return { code: base }; for (let suffix = 2; suffix <= 999; suffix += 1) { const candidate = base + "-" + suffix; if (!used.has(candidate)) return { code: candidate }; } return { error: "Could not generate a unique property code" }; }

export async function createProperty(input: PropertyInput) { const ctx = await setup("real_estate.properties.create"); const generated = input.property_code?.trim() ? { code: input.property_code.trim() } : await generatePropertyCode(ctx, input.name); if (!generated.code) return { errors: { form: generated.error ?? "Could not generate a property code" } }; input = { ...input, property_code: generated.code }; const errors = validateProperty(input); if (Object.keys(errors).length) return { errors }; const { data, error } = await insertProperty(ctx.supabase, ctx, ctx.userId, input); if (error || !data) return { errors: { form: error?.message ?? "Could not create property" } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "property.created", entityType: "property", entityId: data.id, label: input.name }); if (input.auto_generate_inspection_report) { const inspection = await ctx.supabase.schema("real_estate").from("inspections").insert({ organization_id: ctx.organizationId, company_id: ctx.companyId, property_id: data.id, inspection_type: "initial_property_report", status: "scheduled", scheduled_at: new Date().toISOString(), created_by: ctx.userId }).select("id").single(); if (inspection.error || !inspection.data) return { errors: { form: "Property created, but the initial inspection could not be scheduled" } }; } redirect("/real-estate/properties/" + data.id); }
export async function updatePropertyAction(id: string, input: PropertyInput) { const ctx = await setup("real_estate.properties.update"); const errors = validateProperty(input); if (Object.keys(errors).length) return { errors }; const { data, error } = await updateProperty(ctx.supabase, ctx, ctx.userId, id, input); if (error || !data) return { errors: { form: error?.message ?? "Could not update property" } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "property.updated", entityType: "property", entityId: id, label: input.name }); redirect("/real-estate/properties/" + id); }
export async function createUnit(input: UnitInput) { const ctx = await setup("real_estate.units.create"); const errors = validateUnit(input); if (Object.keys(errors).length) return { errors }; const { data, error } = await insertUnit(ctx.supabase, ctx, ctx.userId, input); if (error || !data) { if (error?.code === "23505") return { errors: { unit_number: "That unit number is already active for this property" } }; if (error?.code === "42501" || error?.message?.toLowerCase().includes("row-level security")) return { errors: { form: "You do not have access to add a unit in this property scope" } }; if (error?.code === "23503") return { errors: { property_id: "Choose a valid property" } }; return { errors: { form: "The unit could not be saved. Check the entered details and try again." } }; } await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "unit.created", entityType: "unit", entityId: data.id, label: input.unit_number }); redirect("/real-estate/units/" + data.id); }
export async function updateUnitAction(id: string, input: UnitInput) { const ctx = await setup("real_estate.units.update"); const errors = validateUnit(input); if (Object.keys(errors).length) return { errors }; const { data, error } = await updateUnit(ctx.supabase, ctx, ctx.userId, id, input); if (error || !data) return { errors: { form: error?.message ?? "Could not update unit" } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "unit.updated", entityType: "unit", entityId: id, label: input.unit_number }); redirect("/real-estate/units/" + id); }
export async function createAsset(input: AssetInput) { const ctx = await setup("real_estate.unit_assets.create"); const errors = validateAsset(input); if (Object.keys(errors).length) return { errors }; const { data, error } = await insertAsset(ctx.supabase, ctx, ctx.userId, input); if (error || !data) return { errors: { form: error?.message ?? "Could not create asset" } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "unit_asset.created", entityType: "unit_asset", entityId: data.id }); redirect("/real-estate/units/" + input.unit_id + "/assets"); }
export async function archiveProperty(id: string) { const ctx = await setup("real_estate.properties.archive"); let update = ctx.supabase.schema("real_estate").from("properties").update({ archived_at: new Date().toISOString(), archived_by: ctx.userId }).eq("id", id).eq("organization_id", ctx.organizationId).is("archived_at", null); if (ctx.companyId) update = update.eq("company_id", ctx.companyId); const { error } = await update; if (error) return { errors: { form: error.message } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "property.archived", entityType: "property", entityId: id }); redirect("/real-estate/properties"); }
export async function archiveUnit(id: string) { const ctx = await setup("real_estate.units.archive"); let update = ctx.supabase.schema("real_estate").from("units").update({ archived_at: new Date().toISOString(), archived_by: ctx.userId }).eq("id", id).eq("organization_id", ctx.organizationId).is("archived_at", null); if (ctx.companyId) update = update.eq("company_id", ctx.companyId); const { error } = await update; if (error) return { errors: { form: error.message } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "unit.archived", entityType: "unit", entityId: id }); redirect("/real-estate/units"); }
export async function archiveAsset(id: string, unitId: string) { const ctx = await setup("real_estate.unit_assets.archive"); let update = ctx.supabase.schema("real_estate").from("unit_assets").update({ archived_at: new Date().toISOString(), archived_by: ctx.userId }).eq("id", id).eq("unit_id", unitId).eq("organization_id", ctx.organizationId).is("archived_at", null); if (ctx.companyId) update = update.eq("company_id", ctx.companyId); const { error } = await update; if (error) return { errors: { form: error.message } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "unit_asset.archived", entityType: "unit_asset", entityId: id }); redirect("/real-estate/units/" + unitId + "/assets"); }



