"use server";
import { redirect } from "next/navigation";
import { requirePermission } from "@/lib/auth/server";
import { getRealEstateTenantContext } from "../services/tenant-context";
import { validateProperty, validateUnit, validateAsset, type PropertyInput, type UnitInput, type AssetInput } from "../schemas";
import { insertProperty, updateProperty, insertUnit, updateUnit, insertAsset } from "../repositories";
import { recordRealEstateAudit } from "../services/audit";
async function setup(permission: string) { const ctx = await getRealEstateTenantContext(); if (!ctx.companyId) throw new Error("Select a company before editing Real Estate records"); const auth = await requirePermission(permission, ctx.organizationId, ctx.companyId); return { ...ctx, supabase: auth.supabase, companyId: ctx.companyId }; }
export async function createProperty(input: PropertyInput) { const ctx = await setup("real_estate.properties.create"); const errors = validateProperty(input); if (Object.keys(errors).length) return { errors }; const { data, error } = await insertProperty(ctx.supabase, ctx, ctx.userId, input); if (error || !data) return { errors: { form: error?.message ?? "Could not create property" } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "property.created", entityType: "property", entityId: data.id, label: input.name }); redirect(`/real-estate/properties/${data.id}`); }
export async function updatePropertyAction(id: string, input: PropertyInput) { const ctx = await setup("real_estate.properties.update"); const errors = validateProperty(input); if (Object.keys(errors).length) return { errors }; const { data, error } = await updateProperty(ctx.supabase, ctx, ctx.userId, id, input); if (error || !data) return { errors: { form: error?.message ?? "Could not update property" } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "property.updated", entityType: "property", entityId: id, label: input.name }); redirect(`/real-estate/properties/${id}`); }
export async function createUnit(input: UnitInput) { const ctx = await setup("real_estate.units.create"); const errors = validateUnit(input); if (Object.keys(errors).length) return { errors }; const { data, error } = await insertUnit(ctx.supabase, ctx, ctx.userId, input); if (error || !data) return { errors: { form: error?.code === "23505" ? "That unit number is already active for this property" : error?.message ?? "Could not create unit" } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "unit.created", entityType: "unit", entityId: data.id, label: input.unit_number }); redirect(`/real-estate/units/${data.id}`); }
export async function updateUnitAction(id: string, input: UnitInput) { const ctx = await setup("real_estate.units.update"); const errors = validateUnit(input); if (Object.keys(errors).length) return { errors }; const { data, error } = await updateUnit(ctx.supabase, ctx, ctx.userId, id, input); if (error || !data) return { errors: { form: error?.code === "23505" ? "That unit number is already active for this property" : error?.message ?? "Could not update unit" } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "unit.updated", entityType: "unit", entityId: id, label: input.unit_number }); redirect(`/real-estate/units/${id}`); }
export async function createAsset(input: AssetInput) { const ctx = await setup("real_estate.unit_assets.create"); const errors = validateAsset(input); if (Object.keys(errors).length) return { errors }; const { data, error } = await insertAsset(ctx.supabase, ctx, ctx.userId, input); if (error || !data) return { errors: { form: error?.message ?? "Could not create asset" } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "unit_asset.created", entityType: "unit_asset", entityId: data.id }); redirect(`/real-estate/units/${input.unit_id}/assets`); }
export async function archiveProperty(id: string) { const ctx = await setup("real_estate.properties.archive"); const active = await ctx.supabase.schema("real_estate").from("units").select("id", { count: "exact", head: true }).eq("organization_id", ctx.organizationId).eq("company_id", ctx.companyId).eq("property_id", id).is("archived_at", null); if ((active.count ?? 0) > 0) return { errors: { form: "Archive or reassign active units before archiving this property" } }; const { error } = await ctx.supabase.schema("real_estate").from("properties").update({ archived_at: new Date().toISOString(), archived_by: ctx.userId }).eq("id", id).eq("organization_id", ctx.organizationId).eq("company_id", ctx.companyId).is("archived_at", null); if (error) return { errors: { form: error.message } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "property.archived", entityType: "property", entityId: id }); redirect("/real-estate/properties"); }
export async function archiveUnit(id: string) { const ctx = await setup("real_estate.units.archive"); const { error } = await ctx.supabase.schema("real_estate").from("units").update({ archived_at: new Date().toISOString(), archived_by: ctx.userId }).eq("id", id).eq("organization_id", ctx.organizationId).eq("company_id", ctx.companyId).is("archived_at", null); if (error) return { errors: { form: error.message } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "unit.archived", entityType: "unit", entityId: id }); redirect("/real-estate/units"); }
export async function archiveAsset(id: string, unitId: string) { const ctx = await setup("real_estate.unit_assets.archive"); const { error } = await ctx.supabase.schema("real_estate").from("unit_assets").update({ archived_at: new Date().toISOString(), archived_by: ctx.userId }).eq("id", id).eq("unit_id", unitId).eq("organization_id", ctx.organizationId).eq("company_id", ctx.companyId).is("archived_at", null); if (error) return { errors: { form: error.message } }; await recordRealEstateAudit(ctx.supabase, { userId: ctx.userId, organizationId: ctx.organizationId, companyId: ctx.companyId, action: "unit_asset.archived", entityType: "unit_asset", entityId: id }); redirect(`/real-estate/units/${unitId}/assets`); }
